(function(){try{var h="selectedcontent",b={pluginName:h,_isLoadedAllResources:!1};G_DEPlugin[h]=b;if(DEXTTOP.DEXT5.browser.ie&&7>=DEXTTOP.DEXT5.browser.ieVersion){var w=DEXTTOP.G_CURREDITOR._config.toolBar1.indexOf("p_selectedcontent"),x=DEXTTOP.G_CURREDITOR._config.toolBar2.indexOf("p_selectedcontent");-1<w&&DEXTTOP.G_CURREDITOR._config.toolBar1.splice(w,1);-1<x&&DEXTTOP.G_CURREDITOR._config.toolBar2.splice(x,1)}b._iframe=null;b._iframe_id="";b._self=function(a){return document.getElementById("dext_pan_p_selectedcontent"+
a)};b.isRequiredOtherResource=function(a){var n=setInterval(function(){!0===b._isLoadedAllResources&&(clearInterval(n),a())},50)};b.show=function(a,n){if(0!=G_DEPlugin[h].config.expandMenuList.menuList.length){null==this._iframe&&this.make(a);setFocusTopWindow();G_SUB_DIALOG=this._self(a);G_CURRENT_IFRAME=DEXTTOP.DEXTDOC.getElementById(this._iframe_id);DEXT5_EDITOR.prototype.dialog._click_background(!0);var b={},b=getWindowScrollPos(DEXTTOP.DEXTWIN),e=getClientRect(G_SUB_DIALOG),g=getClientRect(_iframeWin.parent.frameElement),
c=getClientRect(_iframeWin.frameElement),d=180;if(7==DEXTTOP.DEXT5.browser.ieVersion||8==DEXTTOP.DEXT5.browser.ieVersion)d+=2;var m=0;e.left+d>=c.right&&(m=e.left+d-c.right+30);c=0;7==DEXTTOP.DEXT5.browser.ieVersion&&(c=-15);d=0;7==DEXTTOP.DEXT5.browser.ieVersion&&(d=6);isFixedEditorPosition({editor:DEXTTOP.G_CURREDITOR})&&(this._iframe.style.position="fixed",b[0]=0,b[1]=0);d=e.bottom+b[1]+g.top+d;this._iframe.style.left=e.left+b[0]+g.left+c-m+"px";this._iframe.style.top=d+"px";this._iframe.style.display=
"";var k=getIframeDocument(this._iframe);setZoomValueToBody(k,DEXTTOP.G_CURREDITOR);setTimeout(function(){k.getElementsByTagName("A")[0].focus()},1);setFocusFirstAndLast(k,k.getElementsByTagName("A")[0]);DEXTTOP.G_CURREDITOR._dextframeHasFocus=!0}};b.make=function(a){var n=DEXTTOP.DEXT5.GetSelectedContent();if(""!==n.text){var b=this;this._iframe=DEXTTOP.DEXT5.util.makeIframe();this._iframe_id="dext_p_"+h+a;this._iframe.id=this._iframe_id;this._iframe.style.margin="0px";this._iframe.style.padding=
"0px";this._iframe.style.zIndex=G_MAIN_ZINDEX+2E3+"";this._iframe.style.position="absolute";this._iframe.scrolling="no";this._iframe.style.overflow="auto";this._iframe.style.overflowX="hidden";this._iframe.style.display="none";this._iframe.allowTransparency="true";a=0;if(7==DEXTTOP.DEXT5.browser.ieVersion||8==DEXTTOP.DEXT5.browser.ieVersion)a=2;this._iframe.style.width=180+a+"px";a=G_DEPlugin[h].config.expandMenuList.menuList.length;7==DEXTTOP.DEXT5.browser.ieVersion&&(a-=2);a=24*a+2;1!=getDEXTWINZoomValue(DEXTTOP.G_CURREDITOR)&&
(a+=1);this._iframe.style.height=a+"px";this._iframe.frameBorder="0";DEXTTOP.DEXTDOC.body.appendChild(this._iframe);a="document.open();"+(isCustomDomain(document)?'document.domain="'+document.domain+'";':"")+" document.close();";a=DEXTTOP.DEXT5.browser.ie&&12>DEXTTOP.DEXT5.browser.ieVersion?"javascript:void(function(){"+encodeURIComponent(a)+"}())":"";b._iframe.src=a;this._iframe_doc=this._iframe.contentWindow.document;var e="",e=DEXTTOP.DEXT5.isRelease?DEXTTOP.G_CURREDITOR._config.webPath.css:DEXTTOP.G_CURREDITOR._config.webPath.css_dev,
g="editor_context.css";"ko-kr"!=DEXTTOP.G_CURREDITOR._config.lang&&(g="editor_context_"+DEXTTOP.G_CURREDITOR._config.lang+".css");a="<html><head>";isCustomDomain(document)&&(a+='<script>document.domain = "'+document.domain+'";\x3c/script></head>');a+='<link rel="stylesheet" type="text/css" href="'+e+g+"?t="+DEXTTOP.DEXT5.UrlStamp+'" charset="utf-8">';"1"==DEXTTOP.G_CURREDITOR._config.customCssUrlDetailApply&&(a+='<link rel="stylesheet" type="text/css" href="'+DEXTTOP.G_CURREDITOR._config.style.customCssUrl+
"?t="+DEXTTOP.DEXT5.UrlStamp+'" charset="utf-8">');a+='<link rel="stylesheet" type="text/css" href="'+e+"editor_"+DEXTTOP.G_CURREDITOR._config.style.iconName+".css?t="+DEXTTOP.DEXT5.UrlStamp+'" charset="utf-8">';a+='</head><body  style="margin:0px; padding:0px; background-color:transparent;" oncontextmenu="return false"><div onselectstart="return false;" style="width:100%; height:100%" id=p_selectedcontent_iframe_bg">';a+='<div class="DEXT_fiVe_ED_popup">';a+='<div class="DEXT_fiVe_EDP">';a+='<div class="Dfe_popup DEXT_fiVe_'+
DEXTTOP.G_CURREDITOR._config.style.skinName+'">';a+='<dl id="div_p_selectedcontent_main"><dt>selectedcontent_group</dt></dl>';a+="</div>";a+="</div>";a+="</div>";a+="</div>";a+="</body></html>";getDocWindow(this._iframe_doc);this._iframe_doc.open("text/html","replace");this._iframe_doc.write(a);this._iframe_doc.close();a=this._iframe_doc.getElementById("div_p_selectedcontent_main");e=G_DEPlugin[h].config.expandMenuList.menuList.length;for(g=0;g<e;g++){var c=G_DEPlugin[h].config.expandMenuList.menuList[g].command,
d=this._iframe_doc.createElement("dd");d.id=c;var m=DEXTTOP.G_CURREDITOR._config.webPath.plugin+h+"/images/icon_"+c+".png",k=_dext_editor._config.lang,q=G_DEPlugin[h].config.expandMenuList.menuList[g].name[k],k=G_DEPlugin[h].config.expandMenuList.menuList[g].name[k],f=this._iframe_doc.createElement("div"),p=this._iframe_doc.createElement("div"),y=this._iframe_doc.createElement("span");if(0<m.length){y.className=c;var t=this._iframe_doc.createElement("img");t.className=c;t.src=m;t.style.marginTop=
"2px";t.style.border="0px";f.appendChild(t);f.appendChild(y)}"textContent"in p?p.textContent=q:p.innerText=q;f.className="s_left";p.className="s_right";var l=this._iframe_doc.createElement("a");l.href="javascript:void(0);";l.title=k;l.style.textDecoration="none";l.style.color="#545454";l.style.cursor="pointer";l.appendChild(f);l.appendChild(p);d.appendChild(l);var m=function(a){return function(d){DEXTTOP.DEXT5.util.removeEvent(l,"focus",u);DEXTTOP.DEXT5.util.removeEvent(l,"blur",v);"item_disabled"!=
a.className&&(a.className="on_mouseover",DEXTTOP.DEXT5.util.stopEvent(d))}}(d),q=function(a){return function(d){DEXTTOP.DEXT5.util.addEvent(l,"focus",u);DEXTTOP.DEXT5.util.addEvent(l,"blur",v);"on_mouseover"==a.className&&(a.className="",DEXTTOP.DEXT5.util.stopEvent(d))}}(d),u=function(a){return function(d){"item_disabled"!=a.className&&(a.className="on_mouseover",DEXTTOP.DEXT5.util.stopEvent(d))}}(d),v=function(a){return function(d){"on_mouseover"==a.className&&(a.className="",DEXTTOP.DEXT5.util.stopEvent(d))}}(d),
k=function(a){return function(d){_dext_editor._dextCommands(_dext_editor.ID,a.id);b.hide();DEXTTOP.DEXT5.util.stopEvent(d)}}(d);DEXTTOP.DEXT5.util.addEvent(d,"mouseover",m);DEXTTOP.DEXT5.util.addEvent(d,"mouseout",q);DEXTTOP.DEXT5.util.addEvent(d,"click",k);DEXTTOP.DEXT5.util.addEvent(l,"focus",u);DEXTTOP.DEXT5.util.addEvent(l,"blur",v);0<c.length&&(d.id=c);d.unselectable="on";a.appendChild(d);c=function(a){return function(d){command_p_selectedcontent_sub_click(a)}}(d);""!==n.text&&DEXTTOP.DEXT5.util.addEvent(d,
"click",c);DEXTTOP.DEXT5.util.addEvent(b._iframe_doc,"keyup",function(a){27==("which"in a?a.which:a.keyCode)&&(b.hide(),setTimeout(function(){setFocusToBody()},1))})}}};b._addSubItem=function(a,b){var r=DEXTTOP.DEXT5.GetSelectedContent();if(""!==r.text){G_SUB_DIALOG=this._self(_dext_editor.ID);var e=_context_document.createElement("dd"),g=this,c=DEXTTOP.G_CURREDITOR._config.webPath.plugin+h+"/images/icon_"+a+".png",d=_dext_editor._config.lang,m=G_DEPlugin[h].config.expandMenuList.menuList[b].name[d],
d=G_DEPlugin[h].config.expandMenuList.menuList[b].name[d],k=_context_document.createElement("div"),q=_context_document.createElement("div"),f=_context_document.createElement("span");if(0<c.length){f.className=a;var p=_context_document.createElement("img");p.className=a;p.src=c;p.style.marginTop="2px";p.style.border="0px";k.appendChild(p);k.appendChild(f)}"textContent"in q?q.textContent=m:q.innerText=m;k.className="s_left";q.className="s_right";c=_context_document.createElement("a");c.href="javascript:void(0);";
c.title=d;c.style.textDecoration="none";c.style.color="#545454";c.style.cursor="pointer";c.appendChild(k);c.appendChild(q);e.appendChild(c);c=function(a){return function(d){"item_disabled"!=a.className&&(a.className="on_mouseover",DEXTTOP.DEXT5.util.stopEvent(d))}}(e);m=function(a){return function(d){"on_mouseover"==a.className&&(a.className="",DEXTTOP.DEXT5.util.stopEvent(d))}}(e);g=this;d=function(d){return function(c){"on_mouseover"==d.className&&(DEXTTOP.G_CURREDITOR._dextCommands(DEXTTOP.G_CURREDITOR.ID,
a),g.hideSub());null!=DEXTTOP.G_CURREDITOR.dext_dragresize&&DEXTTOP.G_CURREDITOR.dext_dragresize.G_ResizeHandlerActivatedFlag&&(DEXTTOP.G_CURREDITOR.dext_dragresize.G_ResizeHandlerActivatedFlag=!1,DEXTTOP.G_CURREDITOR.dext_dragresize.setResizeHandle(null,!0))}}(e);DEXTTOP.DEXT5.util.addEvent(e,"mouseover",c);DEXTTOP.DEXT5.util.addEvent(e,"mouseout",m);DEXTTOP.DEXT5.util.addEvent(e,"click",d);c=function(a){return function(d){command_p_selectedcontent_sub_click(a)}}(e);""!==r.text&&DEXTTOP.DEXT5.util.addEvent(e,
"click",c);0<a.length&&(e.id=a);e.unselectable="on";DEXT5_CONTEXT._context_sub.appendChild(e)}};b.hide=function(){DEXT5_EDITOR.prototype.dialog._click_background(!0);this._iframe.style.display="none"};b.hideSub=function(){_context_document&&_context_document.getElementById("div_sub_context")&&(_context_document.getElementById("div_sub_context").style.display="none");var a=DEXTTOP.G_CURREDITOR._LastRange?DEXTTOP.G_CURREDITOR._LastRange:getFirstRange().range;restoreSelection(a,!0)};b.onInit=function(){var a=
"../plugin/selectedcontent/js"+(DEXTTOP.DEXT5.isRelease?"":"_dev")+"/config.js",a="1"==DEXTTOP.G_CURREDITOR._config.useConfigTimeStamp?a+("?t="+DEXTTOP.DEXT5.util.getTimeStamp()):a+("?t="+DEXTTOP.DEXT5.UrlStamp),n={url:_dext_editor._config.webPath.plugin+h+"/js"+(DEXTTOP.DEXT5.isRelease?"":"_dev")+"/lang/"+_dext_editor._config.lang+".js",targetDocument:document};loadScript({url:a,targetDocument:document},function(){b._isLoadedAllResources=!0});loadScript(n,null)};b.onClickToolIcon=function(a){try{1!=
b.isProcess&&(b.isProcess=!0,command_p_selectedcontent_click(a))}catch(n){"undefined"!=typeof RAONWIZDLW&&RAONWIZDLW&&RAONWIZDLW()}finally{b.isProcess=!1}};b.onDisableToolIcon=function(a){switch(a){case "cellSelectText":case "selectArea":return!0;default:return["p_selectedcontent"]}};b.onLoaded=function(){var a=_context_document.createElement("div");DEXT5_CONTEXT._setMenuOrg=DEXT5_CONTEXT._setMenu;DEXT5_CONTEXT._setMenu=function(b){DEXT5_CONTEXT._setMenuOrg(b);var r=DEXTTOP.DEXT5.GetSelectedContent();
if(""!==r.text){var e=getDialogDocument().getElementById("dext_context_iframe");if(e){b=this._context_document.createElement("dd");b.id=id="context_p_selectedcontent";b.innerHTML='<div class="s_left"><span style="background: url('+(DEXTTOP.G_CURREDITOR._config.webPath.plugin+h+"/images/icon.png")+') transparent no-repeat;"></span></div><div class="s_right">'+dext5_lang.plugins.selectedcontent.title+"</div>";var g=this._context_document.getElementById("ul_context_main"),c=this._context_document.createElement("dd");
c.className="b_border";g.appendChild(c);g.appendChild(b);b.className=""!==r.text?"":"item_disabled";!0===G_DEPlugin[h].config.expandMenuList.use?(this._width="350px",a.className="arrow",b.appendChild(a),g=function(a){return function(b){if(0==G_DEPlugin[h].config.expandMenuList.menuList.length)a.className="on_mouseover";else{var c=DEXT5_CONTEXT;if("item_disabled"!=a.className){c._context_sub.innerHTML="";for(var e=G_DEPlugin[h].config.expandMenuList.menuList.length,f=0;f<e;f++){if(0==f){var g=c._context_document.createElement("dt");
g.innerHTML="context_sub_menu";c._context_sub.appendChild(g)}G_DEPlugin[h]._addSubItem(G_DEPlugin[h].config.expandMenuList.menuList[f].command,f)}f=b.target?b.target:b.srcElement;e=getClientRect(f);0==e.top&&(e=getClientRect(f));c._context_document.getElementById("div_sub_context").style.display="";var f=getClientRect(c._context_document.getElementById("div_sub_context")),f=f.bottom-f.top,g=getClientRect(c._context_document.getElementById("div_main_context")),n=e.top;e.top+f>g.bottom&&(n=e.top-(e.top+
f-g.bottom));c._context_document.getElementById("div_sub_context").style.top=n+"px";e=getClientRect(c._context_document.getElementById("div_sub_context"));getClientRect(c._context_document.getElementById("div_main_context"));f=getClientRect(c._context_iframe);f=f.bottom-f.top;e.bottom>f&&(e=e.bottom-f,e=parseIntOr0(c._context_iframe.style.height)+e+2,c._context_iframe.style.height=e+"px");a.className="on_mouseover";DEXTTOP.DEXT5.util.stopEvent(b)}}}}(b),c=function(a){return function(a){DEXTTOP.DEXT5.util.stopEvent(a)}}(b),
DEXTTOP.DEXT5.util.addEvent(b,"click",c)):(g=function(a){return function(b){var c=a.className.replace("on_mouseover","");a.className=c+(-1<a.className.indexOf("item_disabled")?"":" on_mouseover");DEXTTOP.DEXT5.util.stopEvent(b)}}(b),c=function(a){return function(b){command_p_selectedcontent_click(a.id)}}(b),""!==r.text&&DEXTTOP.DEXT5.util.addEvent(b,"click",c));r=function(a){return function(b){a.className=a.className.replace("on_mouseover","");DEXTTOP.DEXT5.util.stopEvent(b)}}(b);DEXTTOP.DEXT5.util.addEvent(b,
"mouseover",g);DEXTTOP.DEXT5.util.addEvent(b,"mouseout",r);window.setTimeout(function(){var a=DEXTTOP.DEXT5.util.parseIntOr0(e.style.height);e.style.height=a+26+"px"},1)}}}};b.onInit()}catch(z){"undefined"!=typeof RAONWIZDLW&&RAONWIZDLW&&RAONWIZDLW()}command_p_selectedcontent_click=function(a){!0===G_DEPlugin[h].config.expandMenuList.use?b.show(DEXTTOP.G_CURREDITOR.ID,this):"undefined"!==typeof DEXTTOP.DEXTWIN.dext_editor_plugin_custom_action&&DEXTTOP.DEXTWIN.dext_editor_plugin_custom_action({pluginName:h,
editorID:_dext_editor.ID})};command_p_selectedcontent_sub_click=function(a){"undefined"!==typeof DEXTTOP.DEXTWIN.dext_editor_plugin_custom_action&&DEXTTOP.DEXTWIN.dext_editor_plugin_custom_action({pluginName:h,data:{command:a.id},editorID:_dext_editor.ID})}})();
