(function(){try{var a={pluginName:"webfontloader",configJsLoaded:!1,webFontJsLoaded:!1,isLoadedComplete:!1};G_DEPlugin.webfontloader=a;var f="",g="";a.onInit=function(){f="../plugin/webfontloader/js"+(DEXTTOP.DEXT5.isRelease?"":"_dev")+"/config.js";g="../plugin/webfontloader/js"+(DEXTTOP.DEXT5.isRelease?"":"_dev")+"/webfont.js";"1"==DEXTTOP.G_CURREDITOR._config.useConfigTimeStamp?(f+="?t="+DEXTTOP.DEXT5.util.getTimeStamp(),g+="?t="+DEXTTOP.DEXT5.util.getTimeStamp()):(f+="?t="+DEXTTOP.DEXT5.UrlStamp,
g+="?t="+DEXTTOP.DEXT5.UrlStamp);var h={url:g,targetDocument:document},b={url:_dext_editor._config.webPath.plugin+"webfontloader/js"+(DEXTTOP.DEXT5.isRelease?"":"_dev")+"/lang/"+_dext_editor._config.lang+".js",targetDocument:document};loadScript({url:f,targetDocument:document},a.configLoaded);loadScript(b,null);DEXTTOP.DEXT5.browser.ie?a.webFontJsLoaded=!0:loadScript(h,a.webfontLoaded);var d=setInterval(function(){a.configJsLoaded&&a.webFontJsLoaded&&(clearInterval(d),a.isLoadedComplete=!0)},100)};
a.onLoaded=function(){DEXTTOP.DEXT5.browser.ie?(a.config.uselocalstorage="0",a.loadWebFontCss(_iframeWin)):(!DEXTTOP.DEXT5.browser.LocalStorageSupported&&a.config.uselocalstorage&&(a.config.uselocalstorage="0"),"0"==a.config.uselocalstorage?a.loadWebFontCss(_iframeWin):a.loadWebFontFromLocalStorage(_iframeWin))};a.isRequiredCheck=function(h){return a.isLoadedComplete};a.configLoaded=function(){a.configJsLoaded=!0};a.webfontLoaded=function(){a.webFontJsLoaded=!0};a.loadWebFontCss=function(h){if("1"!=
a.config.uselocalstorage){for(var b=a.config.timeout,b=""==b||0>=parseInt(b)?3E3:parseInt(b),d=a.config.fonts,m=d.length,p=[],c=[],e=0;e<m;e++)""!=d[e].fontCssUrl&&(p=p.concat(d[e].fontFamilies),-1==c.indexOf(d[e].fontCssUrl)&&c.push(d[e].fontCssUrl));d=h.document;m=d.getElementsByTagName("link");for(e=m.length-1;0<=e;e--){for(var l=m[e],f=l.href,k=!1,g=c.length,q=0;q<g;q++)if(-1<f.indexOf(c[q])){k=!0;break}k&&l.parentNode.removeChild(l)}if(DEXTTOP.DEXT5.browser.ie){if(h=0<d.getElementsByTagName("head").length?
d.getElementsByTagName("head")[0]:null)for(e=0;e<c.length;e++)createDynamicCssLinkToHeadTag(d,h,c[e])}else WebFont.load({custom:{families:p,urls:c},context:h,classes:!1,timeout:b})}};a.onAfterDocumentWrite=function(h){switch(h){case "SetHtmlValue":case "SetHtmlValueEx":case "SetHtmlValueExWithDocType":"0"==a.config.uselocalstorage?a.loadWebFontCss(_iframeWin):a.loadWebFontFromLocalStorage(_iframeWin)}};a.loadWebFontFromLocalStorage=function(h){for(var b=a.config.fonts,d=b.length,f=h.document,g=0<
f.getElementsByTagName("head").length?f.getElementsByTagName("head")[0]:null,c=0;c<d;c++)if(1<b[c].fontFamilies.length){for(var e=[],l=[],c=0;c<d;c++)""!=b[c].fontCssUrl&&(e=e.concat(b[c].fontFamilies),-1==l.indexOf(b[c].fontCssUrl)&&l.push(b[c].fontCssUrl));WebFont.load({custom:{families:e,urls:l},context:h,classes:!1,timeout:a.config.timeout})}else{var n=b[c].fontFamilies[0];if(a.isFileSaved(n,b[c].fontCssUrl))a.injectRawStyle(g,localStorage["DEXT5_WEBFONT_"+n]);else{var k=new XMLHttpRequest;k.open("GET",
b[c].fontCssUrl,!1);DEXTTOP.DEXT5.util.setXhrHttpHeader(k,DEXTTOP.G_CURREDITOR._config.addHttpHeader,!1);k.onreadystatechange=function(){4===k.readyState&&(-1<k.responseText.indexOf("data:application/font")||-1<k.responseText.indexOf("data:application/octet-stream")?(a.injectRawStyle(g,k.responseText),localStorage["DEXT5_WEBFONT_"+n]=k.responseText,localStorage["DEXT5_WEBFONT_"+n+"_URL"]=b[c].fontCssUrl):createDynamicCssLinkToHeadTag(f,g,b[c].fontCssUrl))};k.send()}}};a.injectRawStyle=function(a,
b){var d=document.createElement("style");d.setAttribute("type","text/css");d.setAttribute("DEXT5_WEBFONT_BASE64","true");d.styleSheet?d.styleSheet.cssText=b:d.innerHTML=b;a.appendChild(d)};a.isFileSaved=function(a,b){return window.localStorage&&localStorage["DEXT5_WEBFONT_"+a]&&localStorage["DEXT5_WEBFONT_"+a+"_URL"]===b};a.removeBase64WebFontFromHead=function(a){a&&(a=a.replace(/<style type="text\/css" dext5_webfont_base64="true"[^>]*>[^<]*<\/style>/g,""));return a};a.onInit()}catch(r){"undefined"!=
typeof RAONWIZDLW&&RAONWIZDLW&&RAONWIZDLW()}})();
