(function(){try{var b={pluginName:"convertimage",pluginFullName:"p_convertimage"};G_DEPlugin.convertimage=b;b.isSupportBrowser=!0;0!=DEXTTOP.DEXT5.browser.canvasSupported&&"function"==typeof window.Uint16Array||function(){b.isSupportBrowser=!1;_dext_editor._config.removeItem.push(b.pluginFullName);var a=_dext_editor._config.toolbarArr1.indexOf(b.pluginFullName),k=_dext_editor._config.toolbarArr2.indexOf(b.pluginFullName);-1<a&&_dext_editor._config.toolbarArr1.splice(a,1);-1<k&&_dext_editor._config.toolbarArr1.splice(k,
1)}();b.onClickToolIcon=function(a){if(b.isSupportBrowser)switch(a){case b.pluginName:b.start()}};b.onDisableToolIcon=function(a){switch(a){case "":case "default":return!1;case "selectedMultiCell":return[b.pluginFullName];case "focusInCell":return!1;case "focusInCellLockTable":return!1;default:return[b.pluginFullName]}};b.onInit=function(){if(b.isSupportBrowser){var a="../plugin/"+b.pluginName+"/js"+(DEXTTOP.DEXT5.isRelease?"":"_dev")+"/config.js",a="1"==_dext_editor._config.useConfigTimeStamp?a+
("?t="+DEXTTOP.DEXT5.util.getTimeStamp()):a+("?t="+DEXTTOP.DEXT5.UrlStamp),k={url:_dext_editor._config.webPath.plugin+"convertimage/js"+(DEXTTOP.DEXT5.isRelease?"":"_dev")+"/lang/"+_dext_editor._config.lang+".js",targetDocument:document};loadScript({url:a,targetDocument:document},null);loadScript(k,null)}};b.onInit();b.onLoaded=function(){var a=document.getElementById("ue_"+_dext_editor.ID+b.pluginFullName);a&&a.setAttribute("title",b.lang.icon[b.pluginFullName])};b.start=function(){if(DEXTTOP.DEXT5.isEmpty(_dext_editor.ID))alert(b.lang.message.empty);
else{showProcessingBackground();var a=DEXTTOP.DEXT5.getHtmlValueExWithDocType(_dext_editor.ID);b.convertHtmlToImage({strData:a})}};b.convertHtmlToImage=function(a,k){var q=a.strData,m=!0;!1===a.goDownload&&(m=!1);var r=!0===a.sizeFitToContents,h=document.createElement("iframe");document.body.appendChild(h);h.style.opacity=0;h.style.position="absolute";h.style.width="100%";var n=h.contentWindow,c=n.document,p=function(){var a=c.createElement("script");a.onload=function(){var a={allowTaint:!0,useCORS:!0,
logging:!1},f=null;if(!0===r){f=c.createElement("div");for(f.style.display="inline-block";c.body.hasChildNodes();)f.appendChild(c.body.firstChild);c.body.appendChild(f)}else{var f=c.body,d=document.getElementById("ue_editor_holder_"+_dext_editor.ID).style.height,d=DEXTTOP.DEXT5.util.parseIntOr0(d);"number"==typeof d&&0<d&&getClientRect(c.body).bottom<d&&(a.height=d);d=DEXTTOP.DEXT5.util.parseIntOr0(c.body.style.width);if(0<d){var e=DEXTTOP.DEXT5.util.getStyle(c.body,"all"),l=DEXTTOP.DEXT5.util.parseIntOr0(e.marginLeft),
l=DEXTTOP.DEXT5.util.replacePtOrCmToPx(l),l=DEXTTOP.DEXT5.util.parseIntOr0(l),e=DEXTTOP.DEXT5.util.parseIntOr0(e.marginRight),e=DEXTTOP.DEXT5.util.replacePtOrCmToPx(e),e=DEXTTOP.DEXT5.util.parseIntOr0(e);a.width=d+l+e}}n.html2canvas(f,a).then(function(a){var d=b.options.extension;void 0!==_dext_editor.strSavedExtension&&""!==_dext_editor.strSavedExtension&&(d=_dext_editor.strSavedExtension,_dext_editor.strSavedExtension="");var e=b.options.fileName+"."+d,f=a.toDataURL("png"==d?"image/png":"jpg"==
d?"image/jpeg":"image/webp");if(!0===m)if(DEXTTOP.DEXT5.browser.ie)DEXTTOP.navigator.msSaveOrOpenBlob?(a=DEXTTOP.DEXT5.util.dataURItoBlob(f),DEXTTOP.navigator.msSaveOrOpenBlob(a,e),a=null):alert(b.lang.message.error);else{var g=document.createElement("a");g.position="absolute";document.body.appendChild(g);g.href=f;g.target="_self";g.download=e;g.click();setTimeout(function(){try{g.parentNode.removeChild(g),g=null,g=void 0}catch(a){"undefined"!=typeof RAONWIZDLW&&RAONWIZDLW&&RAONWIZDLW()}},100)}hideProcessingBackground();
setTimeout(function(){try{c.body.innerHTML="",h.parentNode.removeChild(h),h=null,h=void 0,"function"===typeof k&&k({imgData:f})}catch(a){"undefined"!=typeof RAONWIZDLW&&RAONWIZDLW&&RAONWIZDLW()}},100)})};a.onerror=function(a){alert(b.lang.message.error+"\n(script not loaded)");hideProcessingBackground()};a.src=_dext_editor._config.webPath.plugin+b.pluginName+"/js"+(DEXTTOP.DEXT5.isRelease?"":"_dev")+"/html2canvas.min.js?t="+DEXTTOP.DEXT5.UrlStamp;c.getElementsByTagName("head")[0].appendChild(a)};
window.convertIframeLoaded=function(){delete window.convertIframeLoaded;if(0==DEXTTOP.DEXT5.browser.ES6Supported){var a=c.createElement("script");a.onload=function(){p()};a.onerror=function(a){alert(b.lang.message.error+"\n(script not loaded)");hideProcessingBackground()};a.src=_dext_editor._config.webPath.plugin+b.pluginName+"/js"+(DEXTTOP.DEXT5.isRelease?"":"_dev")+"/polyfills.umd.js?t="+DEXTTOP.DEXT5.UrlStamp;c.getElementsByTagName("head")[0].appendChild(a)}else p()};c.open();c.write(q+'<script type="text/javascript">document.body.onload = function() { parent.convertIframeLoaded(); }\x3c/script>');
c.close()}}catch(t){"undefined"!=typeof RAONWIZDLW&&RAONWIZDLW&&RAONWIZDLW()}})();
