/*
 GNU Lesser General Public License, http://www.gnu.org/copyleft/lesser.html
 @author  Jan Odvarko, http://odvarko.cz
 @created 2008-06-15
 @updated 2013-04-08
 @link    http://jscolor.com
*/
Array.prototype.indexOf||(Array.prototype.indexOf=function(b,g){g=g||0;for(var c=this.length;g<c;){if(this[g]===b)return g;++g}return-1});
var jscolor={dir:"../images/editor/jscolor/",bindClass:"color",binding:!0,preloading:!0,clickedElem:null,styleColor:"",actionType:"",excuteFn:null,install:function(){jscolor.addEvent(window,"load",jscolor.init)},init:function(){jscolor.binding&&jscolor.bind();jscolor.preloading&&jscolor.preload()},getDir:function(){if(!jscolor.dir){var b=jscolor.detectDir();jscolor.dir=!1!==b?b:"jscolor/"}return jscolor.dir},detectDir:function(){for(var b=location.href,g=document.getElementsByTagName("base"),c=0;c<
g.length;c+=1)g[c].href&&(b=g[c].href);g=document.getElementsByTagName("script");for(c=0;c<g.length;c+=1)if(g[c].src&&/(^|\/)jscolor\.js([?#].*)?$/i.test(g[c].src))return b=(new jscolor.URI(g[c].src)).toAbsolute(b),b.path=b.path.replace(/[^\/]+$/,""),b.query=null,b.fragment=null,b.toString();return!1},bind:function(){for(var b=new RegExp("(^|\\s)("+jscolor.bindClass+")\\s*(\\{[^}]*\\})?","i"),g=document.getElementsByTagName("div"),c=0;c<g.length;c+=1){var p;if(!g[c].color&&g[c].className&&(p=g[c].className.match(b))){var y=
{};if(p[3])try{y=(new Function("return ("+p[3]+")"))()}catch(H){"undefined"!=typeof RAONWIZDLW&&RAONWIZDLW&&RAONWIZDLW()}g[c].color=new jscolor.color(g[c],y)}}},preload:function(){for(var b in jscolor.imgRequire)jscolor.imgRequire.hasOwnProperty(b)&&jscolor.loadImage(b)},images:{pad:[130,81],sld:[15,81],cross:[20,20],arrow:[3,0]},imgRequire:{},imgLoaded:{},requireImage:function(b){jscolor.imgRequire[b]=!0},loadImage:function(b){jscolor.imgLoaded[b]||(jscolor.imgLoaded[b]=new Image,jscolor.imgLoaded[b].src=
(void 0!=parent.DEXTTOP?parent.DEXTTOP:parent.DEXTWIN.DEXTTOP).G_CURREDITOR._config.webPath.image+"jscolor/"+b)},fetchElement:function(b){return"string"===typeof b?document.getElementById(b):b},addEvent:function(b,g,c){b.addEventListener?b.addEventListener(g,c,!1):b.attachEvent&&b.attachEvent("on"+g,c)},fireEvent:function(b,g){if(b)if(document.createEvent){var c=document.createEvent("HTMLEvents");c.initEvent(g,!0,!0);b.dispatchEvent(c)}else if(document.createEventObject)document.createEventObject();
else if(b["on"+g])b["on"+g]()},getElementPos:function(b){var g=b,c=0,p=0;if(g.offsetParent){do c+=g.offsetLeft,p+=g.offsetTop;while(g=g.offsetParent)}for(;(b=b.parentNode)&&"BODY"!==b.nodeName.toUpperCase();)c-=b.scrollLeft,p-=b.scrollTop;return[c,p]},getElementSize:function(b){return[b.offsetWidth,b.offsetHeight]},getRelMousePos:function(b){var g=0,c=0;b||(b=window.event);"number"===typeof b.offsetX?(g=b.offsetX,c=b.offsetY):"number"===typeof b.layerX&&(g=b.layerX,c=b.layerY);return{x:g,y:c}},getViewPos:function(){return"number"===
typeof window.pageYOffset?[window.pageXOffset,window.pageYOffset]:document.body&&(document.body.scrollLeft||document.body.scrollTop)?[document.body.scrollLeft,document.body.scrollTop]:document.documentElement&&(document.documentElement.scrollLeft||document.documentElement.scrollTop)?[document.documentElement.scrollLeft,document.documentElement.scrollTop]:[0,0]},getViewSize:function(){return"number"===typeof window.innerWidth?[window.innerWidth,window.innerHeight]:document.documentElement&&(document.documentElement.clientWidth||
document.documentElement.clientHeight)?[document.documentElement.clientWidth,document.documentElement.clientHeight]:document.body&&(document.body.clientWidth||document.body.clientHeight)?[document.body.clientWidth,document.body.clientHeight]:[0,0]},URI:function(b){function g(c){for(var b="";c;)if("../"===c.substr(0,3)||"./"===c.substr(0,2))c=c.replace(/^\.+/,"").substr(1);else if("/./"===c.substr(0,3)||"/."===c)c="/"+c.substr(3);else if("/../"===c.substr(0,4)||"/.."===c)c="/"+c.substr(4),b=b.replace(/\/?[^\/]*$/,
"");else if("."===c||".."===c)c="";else{var g=c.match(/^\/?[^\/]*/)[0];c=c.substr(g.length);b+=g}return b}this.authority=this.scheme=null;this.path="";this.fragment=this.query=null;this.parse=function(c){c=c.match(/^(([A-Za-z][0-9A-Za-z+.-]*)(:))?((\/\/)([^\/?#]*))?([^?#]*)((\?)([^#]*))?((#)(.*))?/);this.scheme=c[3]?c[2]:null;this.authority=c[5]?c[6]:null;this.path=c[7];this.query=c[9]?c[10]:null;this.fragment=c[12]?c[13]:null;return this};this.toString=function(){var c="";null!==this.scheme&&(c=
c+this.scheme+":");null!==this.authority&&(c=c+"//"+this.authority);null!==this.path&&(c+=this.path);null!==this.query&&(c=c+"?"+this.query);null!==this.fragment&&(c=c+"#"+this.fragment);return c};this.toAbsolute=function(c){c=new jscolor.URI(c);var b=new jscolor.URI;if(null===c.scheme)return!1;null!==this.scheme&&this.scheme.toLowerCase()===c.scheme.toLowerCase()&&(this.scheme=null);null!==this.scheme?(b.scheme=this.scheme,b.authority=this.authority,b.path=g(this.path),b.query=this.query):(null!==
this.authority?(b.authority=this.authority,b.path=g(this.path),b.query=this.query):(""===this.path?(b.path=c.path,b.query=null!==this.query?this.query:c.query):("/"===this.path.substr(0,1)?b.path=g(this.path):(b.path=null!==c.authority&&""===c.path?"/"+this.path:c.path.replace(/[^\/]+$/,"")+this.path,b.path=g(b.path)),b.query=this.query),b.authority=c.authority),b.scheme=c.scheme);b.fragment=this.fragment;return b};b&&this.parse(b)},color:function(b,g,c,p,y,H,L){function A(a,c,h){if(null===a)return[h,
h,h];var b=Math.floor(a),f=h*(1-c);a=h*(1-c*(b%2?a-b:1-(a-b)));switch(b){case 6:case 0:return[h,a,f];case 1:return[a,h,f];case 2:return[f,h,a];case 3:return[f,a,h];case 4:return[a,f,h];case 5:return[h,f,a]}}function M(a,b,h){if(!jscolor.picker){jscolor.picker={box:document.createElement("div"),boxB:document.createElement("div"),pad:document.createElement("div"),padB:document.createElement("div"),padM:document.createElement("div"),sld:document.createElement("div"),sldB:document.createElement("div"),
sldM:document.createElement("div"),btn:document.createElement("div"),boxC:document.createElement("div"),boxHEX:document.createElement("span"),boxRGB:document.createElement("span"),btnS:document.createElement("span"),btnT:document.createTextNode(e.pickerCloseText),select:document.createElement("select"),option1:document.createElement("option"),option2:document.createElement("option"),btnOk:document.createElement("input"),btnCancle:document.createElement("input"),label:document.createElement("label"),
labelR:document.createElement("label"),labelG:document.createElement("label"),labelB:document.createElement("label"),lbColor:document.createElement("input"),lbColor2:document.createElement("input"),lbColorR:document.createElement("input"),lbColorG:document.createElement("input"),lbColorB:document.createElement("input"),inbottom:document.createElement("div"),bottom:document.createElement("div")};for(h=0;h<jscolor.images.sld[1];h+=4){var c=document.createElement("div");c.style.height="4px";c.style.fontSize=
"1px";c.style.lineHeight="0";jscolor.picker.sld.appendChild(c)}jscolor.picker.sldB.appendChild(jscolor.picker.sld);jscolor.picker.box.appendChild(jscolor.picker.sldB);jscolor.picker.box.appendChild(jscolor.picker.sldM);jscolor.picker.padB.appendChild(jscolor.picker.pad);jscolor.picker.box.appendChild(jscolor.picker.padB);jscolor.picker.box.appendChild(jscolor.picker.padM);jscolor.picker.btnS.appendChild(jscolor.picker.btnT);jscolor.picker.btn.appendChild(jscolor.picker.btnS);jscolor.picker.box.appendChild(jscolor.picker.btn);
jscolor.picker.boxB.appendChild(jscolor.picker.box);jscolor.picker.boxC.style.margin="0 0 5px 0";jscolor.picker.boxC.style.padding="0";jscolor.picker.boxC.style.textAlign="left";jscolor.picker.boxC.style.marginBottom="5px";jscolor.picker.lbColor2.setAttribute("type","text");jscolor.picker.lbColor2.setAttribute("id","cp_lb_color2");jscolor.picker.lbColor2.setAttribute("disabled","disabled");jscolor.picker.lbColor2.style.border="solid 1px #c5c5c5";jscolor.picker.lbColor2.style.width="33px";jscolor.picker.lbColor2.style.backgroundColor=
"#ffffff";var f=void 0!=parent.DEXTTOP?parent.DEXTTOP:parent.DEXTWIN.DEXTTOP;h=19;f.DEXT5.browser.ie&&9>=f.DEXT5.browser.ieVersion&&!f.DEXT5.browser.quirks&&(h=15);jscolor.picker.lbColor2.style.height=h+"px";jscolor.picker.lbColor2.style.marginLeft="-1px";jscolor.picker.boxHEX.style.display="inline-block";jscolor.picker.boxHEX.style.margin="0";jscolor.picker.boxHEX.style.padding="0";jscolor.picker.label.innerText="#";jscolor.picker.label.style.marginLeft="1px";jscolor.picker.label.style.color="#5d5d5d";
jscolor.picker.label.style.fontFamily="Tahoma,AppleGothic,sans-serif !important";jscolor.picker.label.style.fontSize="13px";jscolor.picker.lbColor.setAttribute("type","text");jscolor.picker.lbColor.setAttribute("id","cp_lb_color");jscolor.picker.lbColor.style.border="solid 1px #c5c5c5";jscolor.picker.lbColor.style.color="#5d5d5d";jscolor.picker.lbColor.style.fontFamily="Tahoma,AppleGothic,sans-serif !important";jscolor.picker.lbColor.style.fontSize="13px";jscolor.picker.lbColor.style.width=f.DEXT5.browser.ie&&
9>=f.DEXT5.browser.ieVersion&&!f.DEXT5.browser.quirks?"98px":f.DEXT5.browser.chrome?"108px":"107px";jscolor.picker.lbColor.style.height=h+"px";jscolor.picker.lbColor.style.imeMode="disabled";jscolor.picker.lbColor.maxLength="6";f.DEXT5.util.addEvent(jscolor.picker.lbColor,"keyup",function(a){try{jscolor.picker.lbColor2.style.backgroundColor="#"+jscolor.picker.lbColor.value}catch(d){jscolor.picker.lbColor2.style.backgroundColor="#ffffff"}});jscolor.picker.boxHEX.appendChild(jscolor.picker.label);jscolor.picker.boxHEX.appendChild(jscolor.picker.lbColor);
var c="30px",g="3px";f.DEXT5.browser.ie&&9>=f.DEXT5.browser.ieVersion&&!f.DEXT5.browser.quirks?(c="25.5px",g=""):f.DEXT5.browser.chrome&&(c="29.5px");jscolor.picker.labelR.innerText="R";jscolor.picker.labelR.style.color="#5d5d5d";jscolor.picker.labelR.style.fontFamily="Tahoma,AppleGothic,sans-serif !important";jscolor.picker.labelR.style.fontSize="13px";jscolor.picker.labelR.style.marginLeft=g;jscolor.picker.lbColorR.setAttribute("type","text");jscolor.picker.lbColorR.setAttribute("id","cp_lb_color_r");
jscolor.picker.lbColorR.style.border="solid 1px #c5c5c5";jscolor.picker.lbColorR.style.width=c;jscolor.picker.lbColorR.style.height=h+"px";jscolor.picker.lbColorR.style.color="#5d5d5d";jscolor.picker.lbColorR.style.fontFamily="Tahoma,AppleGothic,sans-serif !important";jscolor.picker.lbColorR.style.fontSize="13px";jscolor.picker.lbColorR.style.imeMode="disabled";jscolor.picker.lbColorR.maxLength="3";f.DEXT5.util.addEvent(jscolor.picker.lbColorR,"keypress",function(a){var d=a.keyCode?a.keyCode:a.which;
(48>d||57<d)&&f.DEXT5.util.cancelEvent(a)});f.DEXT5.util.addEvent(jscolor.picker.lbColorR,"keyup",function(a){17==(a.keyCode?a.keyCode:a.which)&&(ctrlDown=!1);0>jscolor.picker.lbColorR.value?jscolor.picker.lbColorR.value=0:255<jscolor.picker.lbColorR.value?jscolor.picker.lbColorR.value=255:"0"!=jscolor.picker.lbColorR.value&&0==jscolor.picker.lbColorR.value.indexOf("0")&&(jscolor.picker.lbColorR.value=jscolor.picker.lbColorR.value.replace("0",""));try{jscolor.picker.lbColor2.style.backgroundColor=
"rgb("+jscolor.picker.lbColorR.value+", "+jscolor.picker.lbColorG.value+", "+jscolor.picker.lbColorB.value+")"}catch(d){jscolor.picker.lbColor2.style.backgroundColor="rgb(255,255,255)"}});jscolor.picker.labelG.innerText="G";jscolor.picker.labelG.style.color="#5d5d5d";jscolor.picker.labelG.style.fontFamily="Tahoma,AppleGothic,sans-serif !important";jscolor.picker.labelG.style.fontSize="13px";jscolor.picker.lbColorG.setAttribute("type","text");jscolor.picker.lbColorG.setAttribute("id","cp_lb_color_g");
jscolor.picker.lbColorG.style.border="solid 1px #c5c5c5";jscolor.picker.lbColorG.style.width=c;jscolor.picker.lbColorG.style.height=h+"px";jscolor.picker.lbColorG.style.color="#5d5d5d";jscolor.picker.lbColorG.style.fontFamily="Tahoma,AppleGothic,sans-serif !important";jscolor.picker.lbColorG.style.fontSize="13px";jscolor.picker.lbColorG.style.imeMode="disabled";jscolor.picker.lbColorG.maxLength="3";f.DEXT5.util.addEvent(jscolor.picker.lbColorG,"keypress",function(a){var d=a.keyCode?a.keyCode:a.which;
(48>d||57<d)&&f.DEXT5.util.cancelEvent(a)});f.DEXT5.util.addEvent(jscolor.picker.lbColorG,"keyup",function(a){0>jscolor.picker.lbColorG.value?jscolor.picker.lbColorG.value=0:255<jscolor.picker.lbColorG.value?jscolor.picker.lbColorG.value=255:"0"!=jscolor.picker.lbColorG.value&&0==jscolor.picker.lbColorG.value.indexOf("0")&&(jscolor.picker.lbColorG.value=jscolor.picker.lbColorG.value.replace("0",""));try{jscolor.picker.lbColor2.style.backgroundColor="rgb("+jscolor.picker.lbColorR.value+", "+jscolor.picker.lbColorG.value+
", "+jscolor.picker.lbColorB.value+")"}catch(d){jscolor.picker.lbColor2.style.backgroundColor="rgb(255,255,255)"}});jscolor.picker.labelB.innerText="B";jscolor.picker.labelB.style.color="#5d5d5d";jscolor.picker.labelB.style.fontFamily="Tahoma,AppleGothic,sans-serif !important";jscolor.picker.labelB.style.fontSize="13px";jscolor.picker.lbColorB.setAttribute("type","text");jscolor.picker.lbColorB.setAttribute("id","cp_lb_color_b");jscolor.picker.lbColorB.style.border="solid 1px #c5c5c5";jscolor.picker.lbColorB.style.width=
c;jscolor.picker.lbColorB.style.height=h+"px";jscolor.picker.lbColorB.style.color="#5d5d5d";jscolor.picker.lbColorB.style.fontFamily="Tahoma,AppleGothic,sans-serif !important";jscolor.picker.lbColorB.style.fontSize="13px";jscolor.picker.lbColorB.style.imeMode="disabled";jscolor.picker.lbColorB.maxLength="3";f.DEXT5.util.addEvent(jscolor.picker.lbColorB,"keypress",function(a){var d=a.keyCode?a.keyCode:a.which;(48>d||57<d)&&f.DEXT5.util.cancelEvent(a)});f.DEXT5.util.addEvent(jscolor.picker.lbColorB,
"keyup",function(a){17==(a.keyCode?a.keyCode:a.which)&&(ctrlDown=!1);0>jscolor.picker.lbColorB.value?jscolor.picker.lbColorB.value=0:255<jscolor.picker.lbColorB.value?jscolor.picker.lbColorB.value=255:"0"!=jscolor.picker.lbColorB.value&&0==jscolor.picker.lbColorB.value.indexOf("0")&&(jscolor.picker.lbColorB.value=jscolor.picker.lbColorB.value.replace("0",""));try{jscolor.picker.lbColor2.style.backgroundColor="rgb("+jscolor.picker.lbColorR.value+", "+jscolor.picker.lbColorG.value+", "+jscolor.picker.lbColorB.value+
")"}catch(d){jscolor.picker.lbColor2.style.backgroundColor="rgb(255,255,255)"}});jscolor.picker.boxRGB.style.margin="0";jscolor.picker.boxRGB.style.padding="0";jscolor.picker.boxRGB.appendChild(jscolor.picker.labelR);jscolor.picker.boxRGB.appendChild(jscolor.picker.lbColorR);jscolor.picker.boxRGB.appendChild(jscolor.picker.labelG);jscolor.picker.boxRGB.appendChild(jscolor.picker.lbColorG);jscolor.picker.boxRGB.appendChild(jscolor.picker.labelB);jscolor.picker.boxRGB.appendChild(jscolor.picker.lbColorB);
jscolor.picker.select.name="colorValue";jscolor.picker.select.id="colorValue";jscolor.picker.select.style.border="1px solid #c5c5c5";jscolor.picker.select.style.color="#5d5d5d";jscolor.picker.select.style.fontFamily="Tahoma,AppleGothic,sans-serif !important";jscolor.picker.select.style.fontSize="13px";"0"==f.G_CURREDITOR._config.colorPickerInputKind?(jscolor.picker.option1.value="hex",jscolor.picker.option1.innerText="HEX",jscolor.picker.option2.value="rgb",jscolor.picker.option2.innerText="RGB"):
"1"==f.G_CURREDITOR._config.colorPickerInputKind&&(jscolor.picker.option1.value="rgb",jscolor.picker.option1.innerText="RGB",jscolor.picker.option2.value="hex",jscolor.picker.option2.innerText="HEX");jscolor.picker.select.appendChild(jscolor.picker.option1);jscolor.picker.select.appendChild(jscolor.picker.option2);jscolor.picker.btnOk.setAttribute("type","button");jscolor.picker.btnOk.setAttribute("id","cp_btn_ok");jscolor.picker.btnOk.setAttribute("value",f.G_CURREDITOR._FRAMEWIN.dext5_lang.color_picker.ok);
jscolor.picker.btnOk.style.width="42px";jscolor.picker.btnOk.style.color="#5d5d5d";jscolor.picker.btnOk.className="DEXT_fiVe_EdiTor_font";jscolor.picker.btnOk.style.fontSize="13px";jscolor.picker.btnCancle.setAttribute("type","button");jscolor.picker.btnCancle.setAttribute("id","cp_btn_cancle");jscolor.picker.btnCancle.setAttribute("value",f.G_CURREDITOR._FRAMEWIN.dext5_lang.color_picker.close);if(h=0==f.DEXT5.UserAgent.os.name.toLowerCase().indexOf("mac")&&"safari"==f.DEXT5.UserAgent.browser.name.toLowerCase())jscolor.picker.btnOk.style.height=
"24px";f.DEXT5.browser.mobile||h?(jscolor.picker.btnCancle.style.width="40px",h&&(jscolor.picker.btnCancle.style.height="24px")):jscolor.picker.btnCancle.style.width=f.DEXT5.browser.ie?"54px":"51px";jscolor.picker.btnCancle.style.color="#5d5d5d";jscolor.picker.btnCancle.className="DEXT_fiVe_EdiTor_font";jscolor.picker.btnCancle.style.fontSize="13px";jscolor.picker.boxC.appendChild(jscolor.picker.lbColor2);"0"==f.G_CURREDITOR._config.colorPickerInputKind?jscolor.picker.boxC.appendChild(jscolor.picker.boxHEX):
"1"==f.G_CURREDITOR._config.colorPickerInputKind&&jscolor.picker.boxC.appendChild(jscolor.picker.boxRGB);jscolor.picker.bottom.appendChild(jscolor.picker.boxC);jscolor.picker.select.onchange=function(){"hex"==jscolor.picker.select.value?(jscolor.picker.lbColor.value="",jscolor.picker.lbColor2.style.backgroundColor="#ffffff",jscolor.picker.boxC.removeChild(jscolor.picker.boxRGB),jscolor.picker.boxHEX.style.display="inline-block",jscolor.picker.boxC.appendChild(jscolor.picker.boxHEX),jscolor.picker.lbColor.focus()):
"rgb"==jscolor.picker.select.value&&(jscolor.picker.lbColorR.value="",jscolor.picker.lbColorG.value="",jscolor.picker.lbColorB.value="",jscolor.picker.lbColor2.style.backgroundColor="#ffffff",jscolor.picker.boxC.removeChild(jscolor.picker.boxHEX),jscolor.picker.boxRGB.style.display="inline-block",jscolor.picker.boxC.appendChild(jscolor.picker.boxRGB),jscolor.picker.lbColorR.focus())};jscolor.picker.inbottom.appendChild(jscolor.picker.select);jscolor.picker.inbottom.appendChild(jscolor.picker.btnOk);
jscolor.picker.inbottom.appendChild(jscolor.picker.btnCancle);jscolor.picker.bottom.appendChild(jscolor.picker.inbottom);jscolor.picker.boxB.appendChild(jscolor.picker.bottom);jscolor.picker.boxB.setAttribute("id","color_picker")}void 0==f&&(f=void 0!=parent.DEXTTOP?parent.DEXTTOP:parent.DEXTWIN.DEXTTOP);var d=jscolor.picker;d.box.onmouseup=d.box.onmousedown=function(){w=!0};d.box.onmousemove=function(a){if(q||r)q&&B(a),r&&C(a),document.selection?document.selection.empty():window.getSelection&&window.getSelection().removeAllRanges(),
x()};"ontouchstart"in window&&d.box.addEventListener("touchmove",function(a){var d={offsetX:a.touches[0].pageX-t.X,offsetY:a.touches[0].pageY-t.Y};if(q||r)q&&B(d),r&&C(d),x();a.stopPropagation();a.preventDefault()},!1);d.padM.onmouseup=d.padM.onmouseout=function(){q&&(q=!1,jscolor.fireEvent(n,"change"))};d.padM.onmousedown=function(a){switch(u){case 0:0===e.hsv[2]&&e.fromHSV(null,null,1);break;case 1:0===e.hsv[1]&&e.fromHSV(null,1,null)}r=!1;q=!0;B(a);x()};"ontouchstart"in window&&d.padM.addEventListener("touchstart",
function(a){t={X:a.target.offsetParent.offsetLeft,Y:a.target.offsetParent.offsetTop};this.onmousedown({offsetX:a.touches[0].pageX-t.X,offsetY:a.touches[0].pageY-t.Y})});d.sldM.onmouseup=d.sldM.onmouseout=function(){r&&(r=!1,jscolor.fireEvent(n,"change"))};d.sldM.onmousedown=function(a){q=!1;r=!0;C(a);x()};"ontouchstart"in window&&d.sldM.addEventListener("touchstart",function(a){t={X:a.target.offsetParent.offsetLeft,Y:a.target.offsetParent.offsetTop};this.onmousedown({offsetX:a.touches[0].pageX-t.X,
offsetY:a.touches[0].pageY-t.Y})});h=I(e);d.box.style.width=h[0]+"px";d.box.style.height=h[1]+"px";d.boxB.style.position="absolute";d.boxB.style.clear="both";d.boxB.style.left=a-6+"px";a=parent.document.getElementById("editor_popup_row_property");h=parent.document.getElementById("editor_popup_column_property");a||h?(b={left:0,top:0,right:0,bottom:0},a&&(b=a.getBoundingClientRect()),h&&(b=h.getBoundingClientRect()),a=parseInt(b.bottom,10)-parseInt(b.top,10),h=parseInt(d.box.style.height.replace("px",
""))+43,b=document.getElementById("color_ul").getBoundingClientRect(),parseInt(b.bottom,10)-parseInt(b.top,10)<h&&(h+=44),d.boxB.style.top=a-h-13+"px"):d.boxB.style.top=b+2+"px";d.boxB.style.zIndex=e.pickerZIndex;d.boxB.style.border=e.pickerBorder+"px solid";d.boxB.style.borderColor=e.pickerBorderColor;d.boxB.style.background=e.pickerFaceColor;d.pad.style.width=jscolor.images.pad[0]+"px";d.pad.style.height=jscolor.images.pad[1]+"px";d.padB.style.position="absolute";d.padB.style.left=e.pickerFace+
"px";d.padB.style.top=e.pickerFace+"px";d.padB.style.border=e.pickerInset+"px solid";d.padB.style.borderColor=e.pickerInsetColor;d.padM.style.position="absolute";d.padM.style.left="0";d.padM.style.top="0";d.padM.style.width=e.pickerFace+2*e.pickerInset+jscolor.images.pad[0]+"px";d.padM.style.height=d.box.style.height;d.padM.style.cursor="crosshair";d.sld.style.overflow="hidden";d.sld.style.width=jscolor.images.sld[0]+"px";d.sld.style.height=jscolor.images.sld[1]+"px";d.sldB.style.display=e.slider?
"block":"none";d.sldB.style.position="absolute";d.sldB.style.right=e.pickerFace+"px";d.sldB.style.top=e.pickerFace+"px";d.sldB.style.border=e.pickerInset+"px solid";d.sldB.style.borderColor=e.pickerInsetColor;d.sldM.style.display=e.slider?"block":"none";d.sldM.style.position="absolute";d.sldM.style.right="3px";d.sldM.style.top="0";d.sldM.style.width=jscolor.images.sld[0]+jscolor.images.arrow[0]+2*e.pickerInset+"px";d.sldM.style.height=d.box.style.height;try{d.sldM.style.cursor="pointer"}catch(l){d.sldM.style.cursor=
"hand"}b=function(a){a=a?a:window.event;if(13==a.keyCode)return m(),!1;a.shiftKey&&9==a.keyCode&&setTimeout(function(){d.btnCancle.focus()},0)};d.lbColor.onkeydown=b;d.lbColorR.onkeydown=b;d.btn.style.display=e.pickerClosable?"block":"none";d.btn.style.position="absolute";d.btn.style.left=e.pickerFace+"px";d.btn.style.bottom=e.pickerFace+"px";d.btn.style.padding="0 15px";d.btn.style.height="18px";d.btn.style.border=e.pickerInset+"px solid";(function(){var a=e.pickerInsetColor.split(/\s+/);d.btn.style.borderColor=
2>a.length?a[0]:a[1]+" "+a[0]+" "+a[0]+" "+a[1]})();d.btn.style.color=e.pickerButtonColor;d.btn.style.font="12px sans-serif";d.btn.style.textAlign="center";try{d.btn.style.cursor="pointer"}catch(k){d.btn.style.cursor="hand"}d.btn.onmousedown=function(){e.hidePicker()};d.btnS.style.lineHeight=d.btn.style.height;var m=function(){var a="",b=d.select.value;if("hex"==b){if(a=d.lbColor.value,null!=a.match(/[^a-f\d]/gi)){alert(f.G_CURREDITOR._FRAMEWIN.dext5_lang.color_picker.msg);setTimeout(function(){d.lbColor.focus()},
0);return}}else{var c=d.lbColorR.value,h=d.lbColorG.value,a=d.lbColorB.value;if(0>=c.length||null!=c.match(/[^0-9\d]/gi)){alert(f.G_CURREDITOR._FRAMEWIN.dext5_lang.color_picker.msg);setTimeout(function(){d.lbColorR.focus()},0);return}if(0>=h.length||null!=h.match(/[^0-9\d]/gi)){alert(f.G_CURREDITOR._FRAMEWIN.dext5_lang.color_picker.msg);setTimeout(function(){d.lbColorG.focus()},0);return}if(0>=a.length||null!=a.match(/[^0-9\d]/gi)){alert(f.G_CURREDITOR._FRAMEWIN.dext5_lang.color_picker.msg);setTimeout(function(){d.lbColorB.focus()},
0);return}c=parseInt(c,10).toString(16);1==c.length&&(c="0"+c);h=parseInt(h,10).toString(16);1==h.length&&(h="0"+h);a=parseInt(a,10).toString(16);1==a.length&&(a="0"+a);a=c+h+a}a=a.replace("#","");c=a.match(/[a-f\d]/gi);if(0>=a.length||null==c)alert(f.G_CURREDITOR._FRAMEWIN.dext5_lang.color_picker.msg),"hex"==b?setTimeout(function(){d.lbColor.focus()},0):setTimeout(function(){d.lbColorR.focus()},0);else if(3==c.length&&(a=c[0]+c[0]+c[1]+c[1]+c[2]+c[2]),3!=c.length&&6!=c.length)alert(f.G_CURREDITOR._FRAMEWIN.dext5_lang.color_picker.msg),
"hex"==b?setTimeout(function(){d.lbColor.focus()},0):setTimeout(function(){d.lbColorR.focus()},0);else if(-1==a.indexOf("#")&&(a="#"+a),7!=a.length)alert(f.G_CURREDITOR._FRAMEWIN.dext5_lang.color_picker.msg),"hex"==b?setTimeout(function(){d.lbColor.focus()},0):setTimeout(function(){d.lbColorR.focus()},0);else{"#000000"==a&&(a="black");a=a.toLowerCase();f.DEXT5.browser.LocalStorageSupported&&(b=f.DEXTWIN.localStorage.getItem(f.G_CURREDITOR.recentlyColorName),null!=b?(b=b.split(","),-1!=b.indexOf(a)&&
b.splice(b.indexOf(a),1),b.unshift(a),9<b.length&&(b.reverse(),b.shift(),b.reverse()),f.DEXTWIN.localStorage.setItem(f.G_CURREDITOR.recentlyColorName,b)):f.DEXTWIN.localStorage.setItem(f.G_CURREDITOR.recentlyColorName,a));void 0!==jscolor.styleColor||""!==jscolor.styleColor?jscolor.clickedElem.style[jscolor.styleColor]=a:(b=iframeDoc.createElement("input"),b.type="hidden",b.value=a,b.id="hidden_color",iframeDoc.body.appendChild(b));if(void 0!==jscolor.actionType||""!==jscolor.actionType)b=L?f.document.getElementById("dext_frame_"+
f.G_CURREDITOR.ID).contentWindow:parent,"font_color"==jscolor.actionType||"detail_font_color"==jscolor.actionType?b.command_fontColor(b.DEXTTOP.G_CURREDITOR.ID,b.document.getElementById("dext5_design_"+b.DEXTTOP.G_CURREDITOR.ID),a):"font_bg_color"==jscolor.actionType||"detail_font_bg_color"==jscolor.actionType?b.command_fontBgColor(b.DEXTTOP.G_CURREDITOR.ID,b.document.getElementById("dext5_design_"+b.DEXTTOP.G_CURREDITOR.ID),a):"doc_bg_color"==jscolor.actionType?b.command_docBGColor(b.DEXTTOP.G_CURREDITOR.ID,
b.document.getElementById("dext5_design_"+b.DEXTTOP.G_CURREDITOR.ID),a):"cell_bg_color"==jscolor.actionType||"detail_cell_bg_color"==jscolor.actionType?b.command_cellBGColor(b.DEXTTOP.G_CURREDITOR.ID,b.document.getElementById("dext5_design_"+b.DEXTTOP.G_CURREDITOR.ID),a):"line_color"==jscolor.actionType&&jscolor.excuteFn&&jscolor.excuteFn();jscolor.clickedElem=null;jscolor.styleColor="";jscolor.actionType="";jscolor.excuteFn=null;parent.document.body.removeChild(parent.document.getElementById("dext_color_back"));
parent.document.body.removeChild(parent.document.getElementById("popupCover"))}};d.btnOk.style.margin="0 2px 0 4px";d.btnOk.onkeydown=function(a){a=a?a:window.event;if(13==a.keyCode)return m(),!1};d.btnOk.onmousedown=m;d.lbColor2.style.margin="0 2px 0 0";d.bottom.style.margin="0 0 3px 6px";var p=function(){jscolor.clickedElem=null;jscolor.styleColor="";jscolor.actionType="";jscolor.excuteFn=null;var a=parent.document.getElementById("popupCover").style.height.replace("px",""),b={left:0,top:0,right:0,
bottom:0},b=document.getElementById("color_picker").getBoundingClientRect(),b=parseInt(b.bottom,10)-parseInt(b.top,10);parent.document.getElementById("popupCover").style.height=a-b+"px";document.getElementById("color_picker").style.display="none"};d.btnCancle.onkeydown=function(a){a=a?a:window.event;13==a.keyCode?p():0==a.shiftKey&&9==a.keyCode&&("hex"==d.select.value?setTimeout(function(){d.lbColor.focus()},0):"rgb"==d.select.value&&setTimeout(function(){d.lbColorR.focus()},0))};d.btnCancle.onmousedown=
p;switch(u){case 0:var v="hs2.png";break;case 1:v="hv.png"}b=f.G_CURREDITOR._config.webPath.image;d.padM.style.backgroundImage="url('"+b+"jscolor/cross.gif')";d.padM.style.backgroundRepeat="no-repeat";d.pad.style.backgroundImage="url('"+b+"jscolor/"+v+"')";d.pad.style.backgroundRepeat="no-repeat";d.pad.style.backgroundPosition="0 0";J();K();jscolor.picker.owner=e;document.getElementsByTagName("body")[0].appendChild(d.boxB)}function I(a){return[2*a.pickerInset+2*a.pickerFace+jscolor.images.pad[0]+
(a.slider?2*a.pickerInset+2*jscolor.images.arrow[0]+jscolor.images.sld[0]:0),a.pickerClosable?4*a.pickerInset+3*a.pickerFace+jscolor.images.pad[1]+a.pickerButtonHeight:2*a.pickerInset+2*a.pickerFace+jscolor.images.pad[1]]}function J(){switch(u){case 0:var a=1;break;case 1:a=2}var b=Math.round(e.hsv[0]/6*(jscolor.images.pad[0]-1)),a=Math.round((1-e.hsv[a])*(jscolor.images.pad[1]-1));jscolor.picker.padM.style.backgroundPosition=e.pickerFace+e.pickerInset+b-Math.floor(jscolor.images.cross[0]/2)+"px "+
(e.pickerFace+e.pickerInset+a-Math.floor(jscolor.images.cross[1]/2))+"px";b=jscolor.picker.sld.childNodes;switch(u){case 0:for(var c=A(e.hsv[0],e.hsv[1],1),a=0;a<b.length;a+=1)b[a].style.backgroundColor="rgb("+c[0]*(1-a/b.length)*100+"%,"+c[1]*(1-a/b.length)*100+"%,"+c[2]*(1-a/b.length)*100+"%)";break;case 1:var g,f=[e.hsv[2],0,0],a=Math.floor(e.hsv[0]),k=a%2?e.hsv[0]-a:1-(e.hsv[0]-a);switch(a){case 6:case 0:c=[0,1,2];break;case 1:c=[1,0,2];break;case 2:c=[2,0,1];break;case 3:c=[2,1,0];break;case 4:c=
[1,2,0];break;case 5:c=[0,2,1]}for(a=0;a<b.length;a+=1)g=1-1/(b.length-1)*a,f[1]=f[0]*(1-g*k),f[2]=f[0]*(1-g),b[a].style.backgroundColor="rgb("+100*f[c[0]]+"%,"+100*f[c[1]]+"%,"+100*f[c[2]]+"%)"}}function K(){switch(u){case 0:var a=2;break;case 1:a=1}a=Math.round((1-e.hsv[a])*(jscolor.images.sld[1]-1));jscolor.picker.sldM.style.backgroundPosition="0 "+(e.pickerFace+e.pickerInset+a-Math.floor(jscolor.images.arrow[1]/2))+"px"}function z(){return jscolor.picker&&jscolor.picker.owner===e}function N(){n!==
b&&e.importColor()}function B(a){var b=jscolor.getRelMousePos(a);a=b.x-e.pickerFace-e.pickerInset;b=b.y-e.pickerFace-e.pickerInset;switch(u){case 0:e.fromHSV(6/(jscolor.images.pad[0]-1)*a,1-b/(jscolor.images.pad[1]-1),null,D);break;case 1:e.fromHSV(6/(jscolor.images.pad[0]-1)*a,null,1-b/(jscolor.images.pad[1]-1),D)}}function C(a){a=jscolor.getRelMousePos(a).y-e.pickerFace-e.pickerInset;switch(u){case 0:e.fromHSV(null,null,1-a/(jscolor.images.sld[1]-1),E);break;case 1:e.fromHSV(null,1-a/(jscolor.images.sld[1]-
1),null,E)}}function x(){e.onImmediateChange&&("string"===typeof e.onImmediateChange?new Function(e.onImmediateChange):e.onImmediateChange).call(e)}jscolor.clickedElem=c;jscolor.styleColor=p;jscolor.actionType=y;jscolor.excuteFn=H;this.slider=this.caps=this.hash=this.adjust=this.required=!0;this.styleElement=this.valueElement=b;this.onImmediateChange=null;this.hsv=[0,0,1];this.rgb=[1,1,1];this.minH=0;this.maxH=6;this.minS=0;this.maxS=1;this.minV=0;this.maxV=1;this.pickerOnfocus=!1;this.pickerMode=
"HSV";this.pickerPosition="bottom";this.pickerSmartPosition=!1;this.pickerButtonHeight=0;this.pickerClosable=!1;this.pickerCloseText="Close";this.pickerButtonColor="ButtonText";this.pickerFace=6;this.pickerFaceColor="ThreeDFace";this.pickerBorder=1;this.pickerBorderColor="ThreeDHighlight ThreeDShadow ThreeDShadow ThreeDHighlight";this.pickerInset=1;this.pickerInsetColor="ThreeDShadow ThreeDShadow ThreeDShadow ThreeDShadow";this.pickerZIndex=15E3;for(var F in g)g.hasOwnProperty(F)&&(this[F]=g[F]);
this.hidePicker=function(){z()&&(delete jscolor.picker.owner,document.getElementsByTagName("body")[0].removeChild(jscolor.picker.boxB))};this.showPicker=function(a){if(!z()){var c="object"==typeof a?a:{};c.preventScroll="boolean"==typeof a.preventScroll?a.preventScroll:!1;var h=jscolor.getElementPos(b),e=jscolor.getElementSize(b),f=jscolor.getViewPos(),g=jscolor.getViewSize(),d=I(this),l,k;switch(this.pickerPosition.toLowerCase()){case "left":a=1;l=0;k=-1;break;case "right":a=1;l=0;k=1;break;case "top":a=
0;l=1;k=-1;break;default:a=0,k=l=1}var m=(e[l]+d[l])/2,h=this.pickerSmartPosition?[-f[a]+h[a]+d[a]>g[a]?-f[a]+h[a]+e[a]/2>g[a]/2&&0<=h[a]+e[a]-d[a]?h[a]+e[a]-d[a]:h[a]:h[a],-f[l]+h[l]+e[l]+d[l]-m+m*k>g[l]?-f[l]+h[l]+e[l]/2>g[l]/2&&0<=h[l]+e[l]-m-m*k?h[l]+e[l]-m-m*k:h[l]+e[l]-m+m*k:0<=h[l]+e[l]-m+m*k?h[l]+e[l]-m+m*k:h[l]+e[l]-m-m*k]:[h[a],h[l]+e[l]-m+m*k];M(h[a],h[l],c)}};this.importColor=function(){n?this.adjust?!this.required&&/^\s*$/.test(n.value)?(n.value="",k.style.backgroundImage=k.jscStyle.backgroundImage,
k.style.backgroundColor=k.jscStyle.backgroundColor,k.style.color=k.jscStyle.color,this.exportColor(v|G)):this.fromString(n.value):this.fromString(n.value,v)||(k.style.backgroundImage=k.jscStyle.backgroundImage,k.style.backgroundColor=k.jscStyle.backgroundColor,k.style.color=k.jscStyle.color,this.exportColor(v|G)):this.exportColor()};this.exportColor=function(a){if(!(a&v)&&n){var b=this.toString(),c=b;this.caps&&(b=b.toUpperCase());null!=jscolor.picker.lbColor&&(jscolor.picker.lbColor.value=b);if(null!=
jscolor.picker.lbColorB){b=c.match(/[a-f\d]/gi);3==b.length&&(c=b[0]+b[0]+b[1]+b[1]+b[2]+b[2]);var b=c.match(/[a-f\d]{2}/gi),c=parseInt(b[0],16),e=parseInt(b[1],16),b=parseInt(b[2],16);jscolor.picker.lbColorR.value=c;jscolor.picker.lbColorG.value=e;jscolor.picker.lbColorB.value=b}}a&G||!k||null==jscolor.picker.lbColor2||(jscolor.picker.lbColor2.style.backgroundColor="#"+this.toString());a&E||!z()||J();a&D||!z()||K()};this.fromHSV=function(a,b,c,e){null!==a&&(a=Math.max(0,this.minH,Math.min(6,this.maxH,
a)));null!==b&&(b=Math.max(0,this.minS,Math.min(1,this.maxS,b)));null!==c&&(c=Math.max(0,this.minV,Math.min(1,this.maxV,c)));this.rgb=A(null===a?this.hsv[0]:this.hsv[0]=a,null===b?this.hsv[1]:this.hsv[1]=b,null===c?this.hsv[2]:this.hsv[2]=c);this.exportColor(e)};this.fromRGB=function(a,b,c,e){null!==a&&(a=Math.max(0,Math.min(1,a)));null!==b&&(b=Math.max(0,Math.min(1,b)));null!==c&&(c=Math.max(0,Math.min(1,c)));a=null===a?this.rgb[0]:a;b=null===b?this.rgb[1]:b;var f=null===c?this.rgb[2]:c,g=Math.min(Math.min(a,
b),f);c=Math.max(Math.max(a,b),f);var d=c-g;0===d?a=[null,0,c]:(a=a===g?3+(f-b)/d:b===g?5+(a-f)/d:1+(b-a)/d,a=[6===a?0:a,d/c,c]);null!==a[0]&&(this.hsv[0]=Math.max(0,this.minH,Math.min(6,this.maxH,a[0])));0!==a[2]&&(this.hsv[1]=null===a[1]?null:Math.max(0,this.minS,Math.min(1,this.maxS,a[1])));this.hsv[2]=null===a[2]?null:Math.max(0,this.minV,Math.min(1,this.maxV,a[2]));a=A(this.hsv[0],this.hsv[1],this.hsv[2]);this.rgb[0]=a[0];this.rgb[1]=a[1];this.rgb[2]=a[2];this.exportColor(e)};this.fromString=
function(a,b){var c="More".match(/^\W*([0-9A-F]{3}([0-9A-F]{3})?)\W*$/i);return c?(6===c[1].length?this.fromRGB(parseInt(c[1].substr(0,2),16)/255,parseInt(c[1].substr(2,2),16)/255,parseInt(c[1].substr(4,2),16)/255,b):this.fromRGB(parseInt(c[1].charAt(0)+c[1].charAt(0),16)/255,parseInt(c[1].charAt(1)+c[1].charAt(1),16)/255,parseInt(c[1].charAt(2)+c[1].charAt(2),16)/255,b),!0):!1};this.toString=function(){return(256|Math.round(255*this.rgb[0])).toString(16).substr(1)+(256|Math.round(255*this.rgb[1])).toString(16).substr(1)+
(256|Math.round(255*this.rgb[2])).toString(16).substr(1)};var e=this,u="hvs"===this.pickerMode.toLowerCase()?1:0,w=!1,n=jscolor.fetchElement(this.valueElement),k=jscolor.fetchElement(this.styleElement),q=!1,r=!1,t={},v=1,G=2,E=4,D=8;jscolor.addEvent(b,"blur",function(){w?w=!1:window.setTimeout(function(){w||(n===b&&e.importColor(),e.pickerOnfocus&&e.hidePicker());w=!1},0)});n&&(g=function(){e.fromString(n.value,v);x()},jscolor.addEvent(n,"keyup",g),jscolor.addEvent(n,"input",g),jscolor.addEvent(n,
"blur",N),n.setAttribute("autocomplete","off"));k&&(k.jscStyle={backgroundImage:k.style.backgroundImage,backgroundColor:k.style.backgroundColor,color:k.style.color});switch(u){case 0:jscolor.requireImage("hs2.png");break;case 1:jscolor.requireImage("hv.png")}jscolor.requireImage("cross.gif");jscolor.requireImage("arrow.gif");this.importColor()}},target=void 0!=parent.DEXTTOP?parent:parent.DEXTWIN;target.DEXTTOP.DEXT5.util.addEvent(document,"contextmenu",function(b){parent.DEXTTOP.DEXT5.util.cancelEvent(b)});
jscolor.install();
