(function(){try{if("undefined"!==typeof _dext_editor){_dext_editor._config.insertMultiImage="1";var b={pluginName:"imageslider"};G_DEPlugin.imageslider=b;b.G_imageslider_imglist=[];b.G_imageslider_imgOrder=[];b.G_IdList=["dext5-imgslider-single","dext5-imgslider-prev","dext5-imgslider-next","dext5-imgslider-dots","dext5-imgslider-viewericon"];b.G_contextSlider=null;b.isSupportBrowser=!0;b.onShowTopMenu=function(a,e){if(!b.isSupportBrowser)return null;switch(a){case "m_insert":return e.push("p_imageslider"),
e;case "m_table":return null;default:return null}};b.insertImageSlider=function(a){""==a.width&&(a.width=_dext_editor._FRAMEWIN._iframeDoc.body.offsetWidth-10);var e=this.makeImageSliderHtml(a.width,a.height,a.useDots,a.useArrows,a.isDragable,a.isRewindable);this.G_imageslider_imglist=[];this.G_imageslider_imgOrder=[];var c=_dext_editor._DOC.defaultView,f=getFirstRange().range,d=getMyElementNode(f.startContainer);"p"!=d.tagName.toLowerCase()||"<br>"!=d.innerHTML&&"<br/>"!=d.innerHTML&&"<br />"!=d.innerHTML&&
""!=d.innerHTML&&"&nbsp;"!=d.innerHTML||f.selectNode(d);_iframeDoc.execCommand("inserthtml",!1,e);if(f=getFirstRange().range)rangy.getSelection(c).removeAllRanges(),rangy.getSelection(c).addRange(f);e={slidesToShow:1,draggable:a.isDragable,rewind:a.isRewindable,callback:function(a){repairBodyFirstLastTag(!0);var c=_dext_editor._DOC;new _dext_editor._EDITOR.design.contentDocument.defaultView.Viewer(a,{inline:!1,navbar:!0,toolbar:!0,title:!0,tooltip:!0,movable:!0,zoomable:!0,scalable:!0,fullscreen:!0,
transition:!0});b.G_IdList.forEach(function(a){(a=c.getElementById(a))&&a.removeAttribute("id")})}};a.useDots&&(e.dots="#dext5-imgslider-dots");a.useArrows&&(e.arrows={prev:"#dext5-imgslider-prev",next:"#dext5-imgslider-next"});new _dext_editor._DOC.defaultView.Dext5ImageSlider(_dext_editor._DOC.getElementById("dext5-imgslider-single"),e)};b.loadImageSlider=function(a){var b=a.getElementsByClassName("dext5-imgslider-contain");Array.from(b).forEach(function(c){var b={slidesToShow:1,skipTrack:!0,draggable:"true"===
c.getAttribute("data-is-dragable"),rewind:"true"===c.getAttribute("data-is-rewindable")};"true"===c.getAttribute("data-use-dots")&&(b.dots=c.getElementsByClassName("dext5-imgslider-dots")[0]);"true"===c.getAttribute("data-use-arrows")&&(b.arrows={prev:c.getElementsByClassName("dext5-imgslider-prev")[0],next:c.getElementsByClassName("dext5-imgslider-next")[0]});b.callback=function(a){new _dext_editor._EDITOR.design.contentDocument.defaultView.Viewer(a,{inline:!1,navbar:!0,toolbar:!0,title:!0,tooltip:!0,
movable:!0,zoomable:!0,scalable:!0,fullscreen:!0,transition:!0})};var d=a.defaultView.Dext5ImageSlider;d||(d=_dext_editor._DOC.defaultView.Dext5ImageSlider);try{new d(c.getElementsByClassName("dext5-imgslider-single")[0],b)}catch(e){"undefined"!=typeof RAONWIZDLW&&RAONWIZDLW&&RAONWIZDLW()}})};b.makeImageSliderHtml=function(a,b,c,f,d,g){a='<div raon_plugin = "imageslider" contenteditable="false" style="width:'+a+"px;height:"+b+'px;" class="dext5-imgslider-contain" data-use-arrows="'+f+'" data-use-dots="'+
c+'" data-is-dragable="'+d+'" data-is-rewindable="'+g+'"><div raon_plugin = "imageslider" id="dext5-imgslider-single" class="dext5-imgslider-single">';b=this.G_imageslider_imglist.length;for(d=0;d<b;d++)a+=this.G_imageslider_imglist[this.G_imageslider_imgOrder[d]];a+="</div>";f&&(a+='<button raon_plugin = "imageslider" role="button" aria-label="Previous" class="dext5-imgslider-prev" id="dext5-imgslider-prev"></button>',a+='<button raon_plugin = "imageslider" role="button" aria-label="Next" class="dext5-imgslider-next" id="dext5-imgslider-next"></button>');
a+='<div raon_plugin = "imageslider" id="dext5-imgslider-viewericon" class="dext5-imgslider-viewericon"></div>';c&&(a+='<div raon_plugin = "imageslider" id="dext5-imgslider-dots" class="dext5-imgslider-dots"></div>');return a+="</div>"};b.onClickToolIcon=function(a){if(b.isSupportBrowser)switch(a){case "imageslider":DEXTTOP.G_SELECTED_ELEMENT=null;DEXT5_EDITOR.prototype.dialog.show(_dext_editor._config.webPath.plugin,"imageslider/editor_popup.html");break;case "property":DEXT5_EDITOR.prototype.dialog.show(_dext_editor._config.webPath.plugin,
"imageslider/editor_property.html")}};b.onDisableToolIcon=function(a){switch(a){case "dextResize":case "selectArea":case "focusImage":case "focusInCell":case "allDisable":return["p_imageslider"];default:return!1}};b.onCreateContextMenu=function(a){!b.isSupportBrowser||-1<a.currElem.className.indexOf("dext5-imgslider-dots")||(this.G_contextSlider=a.currElem.closest(".dext5-imgslider-contain"),a.items=["select_all","","p_imageslider_property"],a.disabledItems=[],a.height="300px",a.width="200px")};b.onAfterEditorChangeMode=
function(a){b.isSupportBrowser&&("preview"==a.newMode?this.loadImageSlider(_dext_editor._EDITOR.preview.contentDocument):"preview"==a.currMode&&"design"==a.newMode&&this.loadImageSlider(_dext_editor._DOC))};b.onBeforeSetCompleteEvent=function(a){this.loadImageSlider(_dext_editor._DOC)};b.onAfterPaste=function(a){this.loadImageSlider(_dext_editor._DOC)};b.onAfterRedo=function(a){this.loadImageSlider(_dext_editor._DOC)};b.onAfterUndo=function(a){this.loadImageSlider(_dext_editor._DOC)};b.onFileChange=
function(a){a.runFlag=!0;"p_imageslider"==a.pageKind&&a.file&&a.file.files&&0==a.file.files.length&&(a.runFlag=!1);return a};b.onBeforeShowContextMenu=function(a){return a};b.onDragResizeMouseDown=function(a){a.runFlag=!0;-1<a.currElem.className.indexOf("dext5-imgslider")&&(DEXTTOP.DEXT5.util.cancelEvent(a.event),a.runFlag=!1);return a};b.onDragResizeMouseOver=function(a){a.runFlag=!0;-1<a.currElem.className.indexOf("dext5-imgslider")&&(DEXTTOP.DEXT5.util.cancelEvent(a.event),a.runFlag=!1);return a};
b.onAfterFileValidation=function(a){"p_imageslider"==a.pageKind&&this._POPUPWIN.addImageOrder(a.files);return a};b.onDbClickImage=function(a){-1<a.elem.className.indexOf("dext5-imgslider")&&(a.runFlag=!1);return a};b.loadModal=function(a){return new Promise(function(b){var c=DEXTTOP.DEXTWIN.document.querySelector("#dext5_imageslider_viewer_"+_dext_editor.ID);null==c?(c=document.createElement("iframe"),c.id="dext5_imageslider_viewer_"+_dext_editor.ID,c.style.position="fixed",c.style.top="0px",c.style.left=
"0px",c.style.border="0px",c.style.backgroundColor="transparent",c.style.width="100%",c.style.height="100%",c.style.display="none",c.style.zIndex=_dext_editor._config.zIndex+1E3,c.src=DEXTTOP.DEXT5.rootPath+"plugin/imageslider/editor_modal.html",c.addEventListener("load",function(){c.contentDocument.body.innerHTML=a.sliderHtmlStr;c.style.display="";setTimeout(function(){(new c.contentDocument.defaultView.Viewer({track:c.contentDocument.querySelector(".dext5-imgslider-track")},{inline:!1,navbar:!0,
toolbar:!0,title:!0,tooltip:!0,movable:!0,zoomable:!0,scalable:!0,fullscreen:!0,transition:!0,isDextEditorPresent:a.isDextEditorPresent,backIframe:c})).view(a.index)},0);b()}),DEXTTOP.DEXTWIN.document.body.appendChild(c)):(c.contentDocument.body.innerHTML=a.sliderHtmlStr,c.style.display="",setTimeout(function(){(new c.contentDocument.defaultView.Viewer({track:c.contentDocument.querySelector(".dext5-imgslider-track")},{inline:!1,navbar:!0,toolbar:!0,title:!0,tooltip:!0,movable:!0,zoomable:!0,scalable:!0,
fullscreen:!0,transition:!0,isDextEditorPresent:a.isDextEditorPresent,backIframe:c})).view(a.index)},0),b())})};b.onInit=function(){if(DEXTTOP.DEXT5.browser.ie&&11>=DEXTTOP.DEXT5.browser.ieVersion||"0"==_dext_editor._config.uploadUseHTML5){b.isSupportBrowser=!1;var a=_dext_editor;a.remove_item.push("p_imageslider");a._config.removeItem.push("p_imageslider")}else a="../plugin/imageslider/js"+(DEXTTOP.DEXT5.isRelease?"":"_dev")+"/config.js",a="1"==_dext_editor._config.useConfigTimeStamp?a+("?t="+DEXTTOP.DEXT5.util.getTimeStamp()):
a+("?t="+DEXTTOP.DEXT5.UrlStamp),a={url:a,targetDocument:document},loadScript({url:_dext_editor._config.webPath.plugin+"imageslider/js"+(DEXTTOP.DEXT5.isRelease?"":"_dev")+"/lang/"+_dext_editor._config.lang+".js",targetDocument:document},null),loadScript(a,null)};b.onInit();b.onLoaded=function(){if(b.isSupportBrowser){var a=DEXTTOP.DEXT5.rootPath+"plugin/imageslider/";_dext_editor._config.xss_allow_url.push(a+"js"+(DEXTTOP.DEXT5.isRelease?"":"_dev")+"/dext5imageslider.js?t="+DEXTTOP.DEXT5.UrlStamp);
DEXTTOP.DEXT5.addUserJsUrl(a+"js"+(DEXTTOP.DEXT5.isRelease?"":"_dev")+"/dext5imageslider.js?t="+DEXTTOP.DEXT5.UrlStamp,_dext_editor.ID);DEXTTOP.DEXT5.addUserCssUrl(a+"css"+(DEXTTOP.DEXT5.isRelease?"":"_dev")+"/dext5imageslider.css?t="+DEXTTOP.DEXT5.UrlStamp,_dext_editor.ID)}}}}catch(h){"undefined"!=typeof RAONWIZDLW&&RAONWIZDLW&&RAONWIZDLW()}})();
