(function(){try{var c={pluginName:"autogrow",maxHeight:null,isScroll:!1};G_DEPlugin.autogrow=c;c.onInit=function(){var a="../plugin/autogrow/js"+(DEXTTOP.DEXT5.isRelease?"":"_dev")+"/config.js",a="1"==DEXTTOP.DEXT5.config.UseConfigTimeStamp?a+("?t="+DEXTTOP.DEXT5.util.getTimeStamp()):a+("?t="+DEXTTOP.DEXT5.UrlStamp),d={url:_dext_editor._config.webPath.plugin+"autogrow/js"+(DEXTTOP.DEXT5.isRelease?"":"_dev")+"/lang/"+_dext_editor._config.lang+".js",targetDocument:document};loadScript({url:a,targetDocument:document},
c.configLoaded);loadScript(d,null)};c.onLoaded=function(){"0"!=DEXTTOP.G_CURREDITOR._config.autoGrowMode&&(G_DEPlugin.autogrow.autoGrowMode=DEXTTOP.G_CURREDITOR._config.autoGrowMode);-1<DEXTTOP.G_CURREDITOR._config.style.height.indexOf("%")&&(DEXTTOP.G_CURREDITOR._config.autoGrowMode="0",G_DEPlugin.autogrow.autoGrowMode="0");if("0"!=G_DEPlugin.autogrow.autoGrowMode||"0"!=DEXTTOP.G_CURREDITOR._config.autoGrowMode)DEXTTOP.G_CURREDITOR._config.useLineBreak="1",DEXTTOP.G_CURREDITOR._config.wordWrapType=
"1",DEXTTOP.G_CURREDITOR._config.resize_bar="0"};c.configLoaded=function(){var a=G_DEPlugin.autogrow.autoGrowMode,d=parseInt(G_DEPlugin.autogrow.maxHeight);if("string"!=typeof a||"0"==G_DEPlugin.autogrow.autoGrowMode)G_DEPlugin.autogrow.autoGrowMode="1";G_DEPlugin.autogrow.autoGrowMode=a;"number"==typeof d&&d&&(d<=parseInt(DEXTTOP.G_CURREDITOR._config.style.height)&&(d=parseInt(DEXTTOP.G_CURREDITOR._config.style.height)),G_DEPlugin.autogrow.maxHeight=d)};c.onChange=function(){c.autogrow(DEXTTOP.G_CURREDITOR)};
c.autogrow=function(a){if("0"!=G_DEPlugin.autogrow.autoGrowMode&&void 0!=G_DEPlugin.autogrow.autoGrowMode)if("full_size"==a.FrameStatus||"design"!=a._currentMode)a._DOC.documentElement.style.overflow="auto";else{var d=a._DOC.documentElement,c=a._BODY,b=DEXTTOP.DEXTDOC.documentElement,h=DEXTTOP.DEXTDOC.body,g=parent.document.getElementById(G_DEPlugin.autogrow.scrollNode);if(void 0==G_DEPlugin.autogrow.configHeight||null==G_DEPlugin.autogrow.configHeight||""==G_DEPlugin.autogrow.configHeight)G_DEPlugin.autogrow.configHeight=
0>a._defaultHeight?parseInt(a._config.style.height,10)-a._defaultHeight:parseInt(a._config.style.height,10),G_DEPlugin.autogrow.initHeight=0<=a._defaultHeight?a._defaultHeight:0,null!=G_DEPlugin.autogrow.maxHeight&&G_DEPlugin.autogrow.isScroll||(d.style.overflowY="hidden"),G_DEPlugin.autogrow.initParentHeight=b.scrollHeight;else{null!=G_DEPlugin.autogrow.maxHeight&&G_DEPlugin.autogrow.isScroll||(d.style.overflowY="hidden");G_DEPlugin.autogrow.previousParentTop=g?g.scrollTop:Math.max(b.scrollTop,h.scrollTop);
setHeight(G_DEPlugin.autogrow.configHeight,a);var f=Math.max(d.scrollHeight,c.scrollHeight),e;if(G_DEPlugin.autogrow.initHeight!=f){e=0==G_DEPlugin.autogrow.initHeight?G_DEPlugin.autogrow.configHeight+(f-a._defaultHeight):G_DEPlugin.autogrow.configHeight+(f-G_DEPlugin.autogrow.initHeight);null!=G_DEPlugin.autogrow.maxHeight&&e>G_DEPlugin.autogrow.maxHeight?(d.style.overflowY="",G_DEPlugin.autogrow.isScroll=!0):G_DEPlugin.autogrow.isScroll=!1;setHeight(e,a);try{d.scrollHeight>d.clientHeight?(e+=d.scrollHeight-
d.clientHeight+1,setHeight(e,a)):c.scrollHeight>c.clientHeight&&(e+=c.scrollHeight-c.clientHeight+1,setHeight(e,a))}catch(l){"undefined"!=typeof RAONWIZDLW&&RAONWIZDLW&&RAONWIZDLW()}}else e=G_DEPlugin.autogrow.configHeight,setHeight(e,a);G_DEPlugin.autogrow.currHeight=f-G_DEPlugin.autogrow.initHeight;G_DEPlugin.autogrow.diffHeight=G_DEPlugin.autogrow.currHeight-G_DEPlugin.autogrow.preHeight;G_DEPlugin.autogrow.preHeight=f-G_DEPlugin.autogrow.initHeight;"2"!=G_DEPlugin.autogrow.autoGrowMode&&(g?g.scrollTop=
G_DEPlugin.autogrow.previousParentTop+G_DEPlugin.autogrow.diffHeight:(b.scrollTop=G_DEPlugin.autogrow.previousParentTop+(b.scrollHeight-G_DEPlugin.autogrow.initParentHeight),h.scrollTop=G_DEPlugin.autogrow.previousParentTop+(b.scrollHeight-G_DEPlugin.autogrow.initParentHeight)),G_DEPlugin.autogrow.previousParentTop=Math.max(b.scrollTop,h.scrollTop),G_DEPlugin.autogrow.initParentHeight=b.scrollHeight);if("2"==G_DEPlugin.autogrow.autoGrowMode)try{"function"===typeof DEXTTOP.DEXTWIN.dext_editor_autogrow_event&&
DEXTTOP.DEXTWIN.dext_editor_autogrow_event(a,{diffHeight:G_DEPlugin.autogrow.diffHeight})}catch(m){"undefined"!=typeof RAONWIZDLW&&RAONWIZDLW&&RAONWIZDLW()}}}};c.onInit()}catch(b){"undefined"!=typeof RAONWIZDLW&&RAONWIZDLW&&RAONWIZDLW()}})();
function setHeight(c,b){var a=b.ID;b=DEXTTOP.DEXT5.util._setDEXT5editor(a);var d=G_DEPlugin.autogrow.maxHeight;null!=d&&c>=d&&(c=d);1==b._config.ruler.use&&1==b._config.ruler.mode&&(d=parseInt(document.getElementById("dext_tab_tool3_"+b.ID).style.height,10),c+=d,DEXTTOP.DEXT5.browser.ie&&7>=DEXTTOP.DEXT5.browser.ieVersion&&(c+=1));if(void 0==a||""==a)a=b.ID;var d=DEXTTOP.DEXTDOC.getElementById("dext_frame_holder"+a),a=DEXTTOP.DEXTDOC.getElementById("dext_frame_"+a).contentWindow.document.getElementById("ue_editor_holder_"+
a),k=0,k=b.baseMenuToolbarHeight;isViewMode(b)?b._defaultHeight=parseInt(c,10)-4:b._defaultHeight=parseInt(c,10)-k;-1<c.toString().indexOf("%")||-1<c.toString().indexOf("px")?d.style.height=c:d.style.height=c+"px";a.style.height=b._defaultHeight+"px";"1"==G_DEPlugin.autogrow.autoGrowMode&&(b._config.style.height=c+"px","1"==b._config.ruler.view&&"design"==b._currentMode&&b._FRAMEWIN.showRuler(b),"1"==b._config.autoBodyFit&&(a=parseIntOr0(b._config.defaultBodySpace.configValue.top)+parseIntOr0(b._config.defaultBodySpace.configValue.bottom),
b._BODY.style.minHeight=(b._defaultHeight-a)/b._defaultHeight*100+"%"))};
