(function(){try{var C=function(){c.G_TABLE_TO_CHART_CURSOR=GetParentbyTagName(getFirstRange().range.startContainer,"table",!0);var b=w(),f=b.length,h=B(b);4>=b.length||b.length==h||b.length==b.length/h?alert(c.lang.message.not_enough_data):(c.G_TABLE_TO_CHART_ROW=f/h,c.G_TABLE_TO_CHART_COLUMN=h,c.G_TABLE_TO_CHART_DATA=b,DEXT5_EDITOR.prototype.dialog.show(_dext_editor._config.webPath.plugin,"chart/editor_popup.html"))},w=function(){var b=GetTableSelectionCells(DEXTTOP.G_SELECTED_ELEMENT,!0);if(1>b.length){var f,
b=[];f=navigator.userAgent.toLowerCase();if(-1<f.indexOf("chrome")||-1<f.indexOf("firefox")||-1<f.indexOf("safari")){f=ActiveCurrTable;for(var c=f.rows.length,g=0,a=0;a<c;a++)for(var n=f.firstElementChild.children[a].childElementCount,d=0;d<n;d++)b[g]=f.firstElementChild.children[a].childNodes[d],g++}else for(f=ActiveCurrTable.cells,c=0;c<f.length;c++)b[c]=f[c]}return b},D=function(){for(var b=w(),c=/colspan="[2-9][0-9]*"/,h=/rowspan="[2-9][0-9]*"/,g=0;g<b.length;g++)if(null!=b[g].outerHTML.match(c)||
null!=b[g].outerHTML.match(h))return!0;return!1},B=function(b){for(var c=v=x=0,h=0,g,a,n=0,d=0;d<b.length;d++)0==d?(g=b[d].cellIndex,a=b[d].cellIndex+b[d].colSpan-1,1<b[d].rowSpan&&x++,1<b[d].colSpan&&(v++,n=b[d].colSpan-1)):(a<b[d].cellIndex+b[d].colSpan-1+n&&(a=b[d].cellIndex+b[d].colSpan-1+n),g==b[d].cellIndex&&(n=0),1<b[d].rowSpan&&(x++,E.push({cellIndex:b[d].cellIndex,rangeIdx:d}),c++),1<b[d].colSpan&&(v++,F.push({cellIndex:b[d].cellIndex,rangeIdx:d}),h++));for(b=0;b<c;b++);for(b=0;b<h;b++);
return a-g+1},c={pluginName:"chart"};G_DEPlugin.chart=c;c.isSupportBrowser=!0;c.onShowTopMenu=function(b,f){if(!c.isSupportBrowser)return null;switch(b){case "m_insert":return f.push("p_chart"),f;case "m_table":return null;default:return null}};c.onResize=function(b){if("end"==b.cmd&&(void 0!=b.isResize||void 0!=b.target)&&c.isSupportBrowser){var f=b.isResize;b=b.target;f&&b&&"img"==b.nodeName.toLowerCase()&&b.getAttribute("raon_chart")?(f={element:b},c.G_TABLE_TO_CHART_CURSOR=null,c.insertChart(f)):
!f&&b&&b.getAttribute("raon_chart")&&(f={element:b},c.G_TABLE_TO_CHART_CURSOR=null,c.insertChart(f))}};c.insertChart=function(b,f){var h=function(a){var b=a.split(",");4==b.length?(b[3]="0.7)",a=b.join()):(a=a.replace(/b/,"ba"),a=a.replace(/\)/,",0.7)"));return a},g=b.element,a=b.chart,n=b.preview;if(null!=g&&!a&&!n){var d=DEXTTOP.DEXT5.util._fn_$mDRM(g.getAttribute("raon_chart")),a=JSON.parse(d.replace(/&quot;/g,'"')).data;a.width=g.clientWidth;a.height=g.clientHeight}var d="line",t={},k={responsive:!1},
z=!0,w=!1,r,m,p,A,v,y,x;yStack=xStack=!1;t.labels=[];for(var e=1;e<a.data.length;e++)t.labels.push(a.data[e][0]);e=a.type.split("-");d=e[0];e=e[1];switch(d){case "line":d="line";r=!1;m=a.color.column;if(2==e||4==e)y=0;if(3==e||4==e)x=0;break;case "bar":d=3==e||4==e?"horizontalBar":"bar";p=a.color.column;if(2==e||4==e)yStack=xStack=!0;break;case "area":d="line";p=a.color.column;r=!0;if(2==e||4==e)y=0;if(3==e||4==e)yStack=!0;break;case "circle":z=!1;1==e?d="pie":2==e&&(d="doughnut");p=a.color.column;
break;case "radar":5==e?(d="polarArea",z=!1,p=a.color.column,k.layout={padding:{top:5,bottom:5}}):(d="radar",1==e?A=p=m=a.color.column:2==e?(p=m=a.color.column,y=0):3==e?(m=a.color.column,r=!1,p=a.color.column,y=0):4==e&&(m=["rgba(0,0,0,0)"],r=!1,v=A=p=a.color.column));break;case "scatter":d=1==e?"scatter":"bubble",w=!0,p=a.color.column}t.datasets=[];var u=0;if(z)for(e=1;e<a.data[0].length;e++){var l={};if(w)if(l.label=a.data[0][e],p&&(l.backgroundColor=p[u]),l.data=[],"scatter"==d)for(var q=1;q<
a.data.length;q++)l.data.push({x:a.data[q][0],y:a.data[q][e]});else{if("bubble"==d){for(q=1;q<a.data.length;q++)l.data.push({x:a.data[q][0],y:a.data[q][e],r:a.data[q][e+1]});e++}}else{l.label=a.data[0][e];l.data=[];for(q=1;q<a.data.length;q++)l.data.push(a.data[q][e]);l.fill=r;l.pointRadius=y;l.lineTension=x;m&&(l.borderColor=m[u]?m[u]:m);p&&(l.backgroundColor=p[u]?h(p[u]):p);A&&(l.pointBorderColor=A[u]);v&&(l.pointBackgroundColor=h(v[u]))}t.datasets.push(l);u++}else{t.labels=a.data[0];l={data:a.data[1],
fill:r,pointRadius:y};m&&(l.borderColor=m);if(p)for(l.backgroundColor=[];u<a.data[0].length;)l.backgroundColor.push(h(p[u++]));t.datasets.push(l)}h=parseFloat(a.axes.max);r=parseFloat(a.axes.min);m=parseFloat(a.axes.step);if(z&&"radar"!=d)k.scales={xAxes:[{stacked:xStack,gridLines:{display:a.grid},scaleLabel:{display:0<a.axes.x.text.length,labelString:a.axes.x.text,fontFamily:a.axes.x.fontFamily,fontSize:a.axes.x.fontSize,fontStyle:a.axes.x.fontStyle,fontColor:a.axes.x.fontColor},ticks:{}}],yAxes:[{stacked:yStack,
gridLines:{display:a.grid},scaleLabel:{display:0<a.axes.y.text.length,labelString:a.axes.y.text,fontFamily:a.axes.y.fontFamily,fontSize:a.axes.y.fontSize,fontStyle:a.axes.y.fontStyle,fontColor:a.axes.y.fontColor},ticks:{}}]},"horizontalBar"==d?(""!=a.axes.max&&(k.scales.xAxes[0].ticks.max=h),""!=a.axes.min&&(k.scales.xAxes[0].ticks.min=r),""!=a.axes.step&&(k.scales.xAxes[0].ticks.stepSize=m)):"scatter"==d||"bubble"==d?(""!=a.axes.max&&(k.scales.xAxes[0].ticks.max=h,k.scales.yAxes[0].ticks.max=h),
""!=a.axes.min&&(k.scales.xAxes[0].ticks.min=r,k.scales.yAxes[0].ticks.min=r),""!=a.axes.step&&(k.scales.xAxes[0].ticks.stepSize=m,k.scales.yAxes[0].ticks.stepSize=m)):(""!=a.axes.max&&(k.scales.yAxes[0].ticks.max=h),""!=a.axes.min&&(k.scales.yAxes[0].ticks.min=r),""!=a.axes.step&&(k.scales.yAxes[0].ticks.stepSize=m));else if("radar"==d||"polarArea"==d)k.scale={ticks:{}},""!=a.axes.max&&(k.scale.ticks.max=h),""!=a.axes.min&&(k.scale.ticks.min=r),""!=a.axes.step&&(k.scale.ticks.stepSize=m);k.title=
{display:0<a.title.text.length,position:a.title.position,text:a.title.text,fontFamily:a.title.fontFamily,fontSize:a.title.fontSize,fontStyle:a.title.fontStyle,fontColor:a.title.fontColor};k.legend={display:a.legend.display,position:a.legend.position,labels:{fontFamily:a.legend.fontFamily,fontSize:parseFloat(a.legend.fontSize),fontStyle:a.legend.fontStyle,fontColor:a.legend.fontColor}};canvas=document.createElement("canvas");a.width=0<parseIntOr0(a.width)?a.width:400;a.height=0<parseIntOr0(a.height)?
a.height:200;canvas.width=a.width;canvas.height=a.height;k.animation={duration:0,onComplete:function(b,d){var e=document.createElement("canvas");e.width=a.width;e.height=a.height;e.getContext("2d").fillStyle=a.color.background;e.getContext("2d").fillRect(this.chartArea.left,this.chartArea.top,this.chartArea.right-this.chartArea.left,this.chartArea.bottom-this.chartArea.top);e.getContext("2d").drawImage(this.canvas,0,0,e.width,e.height);var h=e.toDataURL();if(n)g.width=582<e.width?582:e.width,g.height=
320<e.height?320:e.height,g.src=h;else{if(g)hideDialog(f);else{g=_iframeDoc.createElement("img");e={pluginName:c.pluginName,action:"insert_image",image:g,closeDialog:!!f};if(c.G_TABLE_TO_CHART_CURSOR){var k=c.G_TABLE_TO_CHART_CURSOR;if(!k.nextSibling){var l=_iframeDoc.createElement("p");k.parentNode.appendChild(l)}var l=getFirstRange(),m=l.range;m.setStart(k.nextSibling,0);m.setEnd(k.nextSibling,0);l.sel.removeAllRanges();l.sel.addRange(m);_dext_editor._LastRange=m}event_dext5plugin_action(e,f)}g.src=
h;h=DEXTTOP.DEXT5.util._fn_$mEP(JSON.stringify({data:a}));g.setAttribute("raon_chart",h);g.style.width=a.width+"px";g.style.height=a.height+"px"}}};new Chart(canvas,{type:d,data:t,options:k})};c.onClickToolIcon=function(b){if(c.isSupportBrowser)switch(c.G_TABLE_TO_CHART_DATA=null,c.G_TABLE_TO_CHART_COLUMN=null,c.G_TABLE_TO_CHART_ROW=null,c.G_TABLE_TO_CHART_CURSOR=null,b){case "chart":DEXTTOP.G_SELECTED_ELEMENT=null;DEXT5_EDITOR.prototype.dialog.show(_dext_editor._config.webPath.plugin,"chart/editor_popup.html");
break;case "tabletochart":c.tableToChart();case "chartproperty":DEXT5_EDITOR.prototype.dialog.show(_dext_editor._config.webPath.plugin,"chart/editor_popup.html")}};c.onDisableToolIcon=function(b){switch(b){case "":case "default":return["p_chart_tabletochart"];case "selectedMultiCell":return["p_chart"];case "focusInCell":return!1;case "focusInCellLockTable":return!1;default:return["p_chart","p_chart_tabletochart"]}};c.onCreateContextMenu=function(b){c.isSupportBrowser&&(b.items="paste cut copy  select_all  p_chart_chartproperty".split(" "),
b.disabledItems=["paste"],b.height="300px",b.width="200px")};c.onDbClickImage=function(b){if(c.isSupportBrowser)return c.G_TABLE_TO_CHART_DATA=null,c.G_TABLE_TO_CHART_COLUMN=null,c.G_TABLE_TO_CHART_ROW=null,c.G_TABLE_TO_CHART_CURSOR=null,DEXT5_EDITOR.prototype.dialog.show(_dext_editor._config.webPath.plugin,"chart/editor_popup.html"),b.runFlag=!1,b};c.onInit=function(){if(!DEXTTOP.DEXT5.browser.canvasSupported||DEXTTOP.DEXT5.browser.ie&&9>DEXTTOP.DEXT5.browser.ieVersion){c.isSupportBrowser=!1;var b=
_dext_editor;b.remove_item.push("p_chart");b.remove_item.push("p_chart_tabletochart")}else{var b="../plugin/chart/js"+(DEXTTOP.DEXT5.isRelease?"":"_dev")+"/config.js",b="1"==DEXTTOP.DEXT5.config.UseConfigTimeStamp?b+("?t="+DEXTTOP.DEXT5.util.getTimeStamp()):b+("?t="+DEXTTOP.DEXT5.UrlStamp),b={url:b,targetDocument:document},f={url:"../plugin/chart/js"+(DEXTTOP.DEXT5.isRelease?"":"_dev")+"/chart.js?t="+DEXTTOP.DEXT5.UrlStamp,targetDocument:document},h={url:"../plugin/chart/js"+(DEXTTOP.DEXT5.isRelease?
"":"_dev")+"/grid.js?t="+DEXTTOP.DEXT5.UrlStamp,targetDocument:document};loadScript({url:_dext_editor._config.webPath.plugin+"chart/js"+(DEXTTOP.DEXT5.isRelease?"":"_dev")+"/lang/"+_dext_editor._config.lang+".js",targetDocument:document},null);loadScript(b,null);loadScript(f,null);loadScript(h,null)}};c.onInit();c.onLoaded=function(){c.isSupportBrowser&&(DEXT5_CONTEXT._item_sub_list.table_tool.push("p_chart_tabletochart"),DEXT5_TOPMENU._item_sub_list.table_tool.push("p_chart_tabletochart"))};var x=
0,v=0,E=[],F=[];c.tableToChart=function(){restoreSelection();var b=w(),f,h,g=0;if(c.allowMergedTableToChart)if(h=B(b),4>=b.length||b.length==h||b.length==b.length/h)alert(c.lang.message.not_enough_data);else{f=b.length;g=0;f=[];for(var a=0,n=0;b[g];){a=0;rowPos=parseInt(g/h);if(1<b[g].colSpan){for(a=2;a<=b[g].colSpan;a++)b.splice(g+a-1,0,"0");for(var a=0,d=2;d<=b[g].rowSpan;){for(var t=2;t<=b[g].colSpan;t++)f.push(g+n+((d-1)*h+t-1)),a++;f.push(g+n+(d-1)*h);a++;d++}n+=a}else if(1<b[g].rowSpan){for(d=
2;d<=b[g].rowSpan;d++)f.push(g+n+h*(d-1)),a++;n+=a}g++}f=f.sort(function(a,b){return a-b});for(g=0;g<f.length;g++)b.splice(f[g],0,"0");f=b.length;f/=h;c.G_TABLE_TO_CHART_ROW=f;c.G_TABLE_TO_CHART_DATA=b;c.G_TABLE_TO_CHART_COLUMN=h;f!==parseInt(f)?alert(c.lang.message.incorrect_selection):(c.G_TABLE_TO_CHART_CURSOR=GetParentbyTagName(getFirstRange().range.startContainer,"table",!0),DEXT5_EDITOR.prototype.dialog.show(_dext_editor._config.webPath.plugin,"chart/editor_popup.html"))}else D()?alert(c.lang.message.merge):
C()}}catch(G){"undefined"!=typeof RAONWIZDLW&&RAONWIZDLW&&RAONWIZDLW()}})();
