(function(){try{var c={pluginName:"customformatting",_isLoadedAllResources:!1};G_DEPlugin.customformatting=c;removeToolbarIcon=function(){var a=DEXTTOP.G_CURREDITOR._config.toolBar1.indexOf("p_customformatting"),g=DEXTTOP.G_CURREDITOR._config.toolBar2.indexOf("p_customformatting");-1<a&&DEXTTOP.G_CURREDITOR._config.toolBar1.splice(a,1);-1<g&&DEXTTOP.G_CURREDITOR._config.toolBar2.splice(g,1)};DEXTTOP.DEXT5.browser.ie&&12>DEXTTOP.DEXT5.browser.ieVersion&&removeToolbarIcon();c.isRequiredOtherResource=
function(a){var g=setInterval(function(){!0===c._isLoadedAllResources&&(clearInterval(g),1>G_DEPlugin.customformatting.config.setting.formattingList.length&&removeToolbarIcon(),a())},50)};c.onInit=function(){var a="../plugin/customformatting/js"+(DEXTTOP.DEXT5.isRelease?"":"_dev")+"/config.js",a="1"==DEXTTOP.G_CURREDITOR._config.useConfigTimeStamp?a+("?t="+DEXTTOP.DEXT5.util.getTimeStamp()):a+("?t="+DEXTTOP.DEXT5.UrlStamp);loadScript({url:a,targetDocument:document},function(){c._isLoadedAllResources=
!0})};c.onInit();c._iframeHolder=null;c._iframeHolder_id="";c._iframe=null;c._iframe_id="";c._iframe_doc=null;c._self=function(a){return document.getElementById("dext_pan_p_customformatting_"+a)};c.init=function(a){document.getElementById("ue_"+a+"p_customformatting")&&(document.getElementById("ue_"+a+"p_customformatting").innerHTML="<span>"+G_DEPlugin.customformatting.config.setting.defaultTitle[_dext_editor._config.lang]+"</span>")};c.make=function(a,g){var e=DEXTTOP.DEXTDOC.getElementById("dext_customformatting_iframe_"+
a);e&&e.parentNode.removeChild(e);(e=DEXTTOP.DEXTDOC.getElementById("dext_customformatting_iframe_holder_"+a))&&e.parentNode.removeChild(e);var h=this;if(null!=h._self(a)){var d;0<G_DEPlugin.customformatting.config.setting.formattingList.length&&(h._format=G_DEPlugin.customformatting.config.setting.formattingList);e=h._format.length;this._iframe=DEXTTOP.DEXT5.util.makeIframe();this._iframe.title=dext5_lang.iframe_title.customformatting;this._iframe_id="dext_customformatting_iframe_"+a;this._iframe.id=
this._iframe_id;this._iframe.style.display="none";DEXTTOP.DEXT5.browser.iOS||DEXTTOP.DEXT5.browser.mobile?(this._iframe.width="100%",this._iframe.height="100%",this._iframe.style.overflow="hidden",this._iframe.style.display="inline-block",this._iframeHolder=DEXTTOP.DEXTDOC.createElement("div"),this._iframeHolder_id="dext_customformatting_iframe_holder_"+a,this._iframeHolder.id=this._iframeHolder_id,this._iframeHolder.style.display="none",this._iframeHolder.style.width="230px",this._iframeHolder.style.height=
"150px",this._iframeHolder.style.border="2px solid #cccccc",this._iframeHolder.style.zIndex=G_MAIN_ZINDEX+2E3+"",this._iframeHolder.style.position="absolute",this._iframeHolder.style.overflow="scroll",this._iframeHolder.style.overflowX="hidden",this._iframeHolder.style.webkitOverflowScrolling="touch",this._iframeHolder.appendChild(this._iframe),DEXTTOP.DEXTDOC.body.appendChild(this._iframeHolder)):(this._iframe.style.zIndex=G_MAIN_ZINDEX+2E3+"",this._iframe.style.border="2px solid #cccccc",this._iframe.style.position=
"absolute",this._iframe.width="230px",this._iframe.height="230px",this._iframe.style.width="230px",this._iframe.style.height=7>e?35*e+"px":"230px",DEXTTOP.DEXTDOC.body.appendChild(this._iframe));d="document.open();"+(isCustomDomain(document)?'document.domain="'+document.domain+'";':"")+" document.close();";d=DEXTTOP.DEXT5.browser.ie&&12>DEXTTOP.DEXT5.browser.ieVersion?"javascript:void(function(){"+encodeURIComponent(d)+"}())":"";this._iframe.src=d;this._iframe_doc=this._iframe.contentWindow.document;
d="";isRTL(document)&&(d=' dir="rtl"');d="<html"+d+"><head><title>"+dext5_lang.formatting.custom_format+"</title>";isCustomDomain(document)&&(d+='<script>document.domain = "'+document.domain+'";\x3c/script></head>');""!=DEXTTOP.G_CURREDITOR._config.webFontCssUrl&&(d+='<link href="'+DEXTTOP.G_CURREDITOR._config.webFontCssUrl+'" rel="stylesheet" type="text/css">');d+='</head><body style="margin:0px; padding:0px; " oncontextmenu="return false"></body></html>';getDocWindow(this._iframe_doc);this._iframe_doc.open("text/html",
"replace");this._iframe_doc.write(d);this._iframe_doc.close();h=this;if(G_DEPlugin.webfontloader){var c=function(a){"0"==G_DEPlugin.webfontloader.config.uselocalstorage?G_DEPlugin.webfontloader.loadWebFontCss(a):G_DEPlugin.webfontloader.loadWebFontFromLocalStorage(a)};if(G_DEPlugin.webfontloader.isRequiredCheck())c(h._iframe.contentWindow);else var b=setInterval(function(){G_DEPlugin.webfontloader.isRequiredCheck()&&(clearInterval(b),c(h._iframe.contentWindow))},100)}for(var m=G_DEPlugin.customformatting.config.setting.formattingList,
n=0;n<e;n++){var f=m[n],t="fs_"+a+"_"+n;d=this._iframe_doc.createElement("div");d.setAttribute("id",t);d.style.whiteSpace="nowrap";d.style.width="96%";d.style.cursor="pointer";d.style.padding="3px";d.style.margin="3px";_item_text=this._iframe_doc.createElement("span");var B=f;"textContent"in _item_text?_item_text.textContent=B.name[_dext_editor._config.lang]:_item_text.innerText=B.name[_dext_editor._config.lang];_item_text.setAttribute("style",f.style);_item_text.onmousedown=function(){return!1};
_item_text.unselectable="on";_a_tag=this._iframe_doc.createElement("a");_a_tag.href="javascript:void(0);";_a_tag.appendChild(_item_text);_a_tag.style.textDecoration="none";_a_tag.style.color="black";f=function(b){return function(d){h.mouseover_func(a,b);DEXTTOP.DEXT5.util.stopEvent(d)}}(t);t=function(b){return function(d){h.click_func(a,b);DEXTTOP.DEXT5.util.stopEvent(d)}}(n);DEXTTOP.DEXT5.util.addEvent(d,"mouseover",f);DEXTTOP.DEXT5.util.addEvent(d,"click",t);d.onmousedown=function(){return!1};d.unselectable=
"on";d.appendChild(_a_tag);this._iframe_doc.body.appendChild(d)}document.getElementById("ue_"+a+"p_customformatting").innerHTML="<span>"+G_DEPlugin.customformatting.config.setting.defaultTitle[_dext_editor._config.lang]+"</span>";DEXTTOP.DEXT5.util.addEvent(h._iframe_doc,"keyup",function(b){27==("which"in b?b.which:b.keyCode)&&(h.hide(a),setTimeout(function(){setFocusToBody()},1))})}};c.mouseover_func=function(a,g){this.reset(a);this._iframe_doc.getElementById(g).style.backgroundColor="#e7e7e7"};
c.click_func=function(a,g){var e=this.get_value(a,g);document.getElementById("ue_"+a+"p_customformatting").innerHTML="<span>"+e+"</span>";command_customformatting(a,document.getElementById("dext5_design_"+a),e,g);this.hide(a)};c.show=function(a){null!=this._iframe&&"ios"!=DEXTTOP.DEXT5.UserAgent.os.name.toLowerCase()||this.make(a,DEXTTOP.G_CURREDITOR._config);G_SUB_DIALOG=this._self(a);G_CURRENT_IFRAME=DEXTTOP.DEXTDOC.getElementById(this._iframe_id);this._iframeHolder&&(G_CURRENT_IFRAME_HOLDER=DEXTTOP.DEXTDOC.getElementById(this._iframeHolder.id));
this.reset(a);DEXT5_EDITOR.prototype.dialog._click_background(!0);var g={},g=getWindowScrollPos(DEXTTOP.DEXTWIN),e=getClientRect(_iframeWin.parent.frameElement),h=getClientRect(_iframeWin.parent.frameElement.contentWindow.document.getElementById("ue_"+a+"p_customformatting")),d=0;7==DEXTTOP.DEXT5.browser.ieVersion&&(d=-2);isFixedEditorPosition({editor:DEXTTOP.G_CURREDITOR})&&(this._iframe.style.position="fixed",g[0]=0,g[1]=0);var c=h.left+g[0]+e.left;isRTL(document)&&(c=this._iframeHolder?DEXTTOP.DEXT5.util.parseIntOr0(this._iframeHolder.style.width):
DEXTTOP.DEXT5.util.parseIntOr0(this._iframe.style.width),c=h.right+g[0]+e.left-(c+4),0>c&&(c=10));g=h.bottom+g[1]+e.top+d;this._iframeHolder?(this._iframeHolder.style.left=c+"px",this._iframeHolder.style.top=g+"px",this._iframeHolder.style.display=""):(this._iframe.style.left=c+"px",this._iframe.style.top=g+"px");this._iframe.style.display="";var g=this._iframe.contentWindow,b=getIframeDocument(this._iframe);setZoomValueToBody(b,DEXTTOP.G_CURREDITOR);0==DEXTTOP.DEXT5.browser.ie&&g.focus();setTimeout(function(){b.getElementsByTagName("A")[0].focus()},
1);setFocusFirstAndLast(b,b.getElementsByTagName("A")[0]);DEXTTOP.G_CURREDITOR._dextframeHasFocus=!0;try{"function"==typeof DEXTTOP.G_CURREDITOR._config.event.afterPopupShow?DEXTTOP.G_CURREDITOR._config.event.afterPopupShow(a,this._iframe,"customformatting"):"function"==typeof DEXTTOP.dext_editor_afterpopupshow_event&&DEXTTOP.dext_editor_afterpopupshow_event(a,this._iframe,"customformatting")}catch(m){"undefined"!=typeof RAONWIZDLW&&RAONWIZDLW&&RAONWIZDLW()}};c.hide=function(a){dialogCancel();G_SUB_DIALOG=
this._self(a);this.reset(a);DEXT5_EDITOR.prototype.dialog._click_background(!0);this._iframe.style.display="none";this._iframeHolder&&(this._iframeHolder.style.display="none")};c.reset=function(a){for(var g=this._iframe_doc.getElementsByTagName("div").length,e,c=0;c<g;c++)e="fs_"+a+"_"+c,this._iframe_doc.getElementById(e).style.backgroundColor=""};c.get_value=function(a,c){return G_DEPlugin.customformatting.config.setting.formattingList[c].name[_dext_editor._config.lang]};c.onClickToolIcon=function(a){try{1!=
c.isProcess&&(c.isProcess=!0,command_p_customformatting_click(a))}catch(g){"undefined"!=typeof RAONWIZDLW&&RAONWIZDLW&&RAONWIZDLW()}finally{c.isProcess=!1}};c.onDisableToolIcon=function(a){switch(a){case "allDisable":return["p_customformatting"];default:return!0}};c.getCustomformattingName=function(a,c){var e=document.getElementById("ue_"+a+"p_customformatting"),h=!1;if(e&&e.hasChildNodes()){var d=G_DEPlugin.customformatting.config.setting.formattingList,r=c.getAttribute("style");if(null!=r)for(var b=
0;b<d.length;b++){for(var m=r.split(";"),n=0,f=0;f<m.length;f++)-1<d[b].style.indexOf(m[f].trim())&&n++;n==m.length&&(e.firstChild.textContent=d[b].name[_dext_editor._config.lang],h=!0)}h||(e.firstChild.textContent=G_DEPlugin.customformatting.config.setting.defaultTitle[_dext_editor._config.lang])}};command_customformatting=function(a,g,e,h){dext_src_init(g);e.toLowerCase();restoreSelection();setFocusToBody();var d=getFirstRange();a=d.range;g=!1;if(0==a.collapsed){var r=a.endContainer;0==(3==a.startContainer.nodeType&&
3==r.nodeType)&&(g=!0,adjustSelectionExcludingNextLineStart(d,a))}d=c.config.setting.formattingList[h].style;h=c.config.setting.formattingList[h].styleType;DoExecuteCommandFormatting_plugin(a,e,!0,"block"===h?"span":"p",d);g&&(removeDextMarkInFrame(),(e=_iframeDoc.getElementById("de_temp_start_span"))&&e.parentNode.removeChild(e),(e=_iframeDoc.getElementById("de_temp_end_span"))&&e.parentNode.removeChild(e))};DoExecuteCommandFormatting_plugin=function(a,c,e,h,d){try{(null==DEXTTOP.G_CURREDITOR._formatPainterList||
DEXTTOP.G_CURREDITOR._formatPainterList&&"1"!=DEXTTOP.G_CURREDITOR._formatPainterList.nowApplying)&&0<DEXTTOP.G_CURREDITOR.UndoManager.charCount&&(DEXTTOP.G_CURREDITOR.UndoManager.putUndo(),DEXTTOP.G_CURREDITOR.UndoManager.canUndo=!0,DEXTTOP.G_CURREDITOR.UndoManager.isInsertData=!0,DEXTTOP.G_CURREDITOR._iconEnable(""));var r=function(a,b){var c=_iframeDoc.createElement("p");c.innerHTML="p"==b?a.innerHTML:a.textContent;a.parentNode.replaceChild(c,a);return c};if("p"===h){var b=DEXTTOP.DEXT5.getCaretElement(DEXTTOP.G_CURREDITOR.ID),
m,n=_iframeDoc.getSelection();if(1==a.collapsed){if("li"!=b.tagName.toLowerCase()){for(;"P"!=b.tagName;)if(-1<b.tagName.indexOf("H")){var b=r(b,h),f=document.createRange();f.setStart(b,0);f.setEnd(b,1);n.removeAllRanges();n.addRange(f);a=f}else if("body"==b.tagName.toLowerCase())break;else b=b.parentNode;var t=GetTableSelectionCells();if(0==t.length)b.setAttribute("style",d);else for(var B=t.length,y=0,l=0;l<B;l++)for(var I=getFormattingNode(t[l],c,e,!0),y=I.length,v=0;v<y;v++)I[v].setAttribute("style",
d)}}else{var k=a.startContainer,p=a.endContainer;if(3!=k.nodeType&&"body"==k.tagName.toLowerCase())for(k=k.firstChild;"table"!=k.tagName.toLowerCase();)k=k.nextSibling;for(;"3"==k.nodeType;)k=k.parentNode;for(;"3"==p.nodeType;)p=p.parentNode;for(;"P"!=k.tagName&&0>k.tagName.indexOf("H")&&"table"!=k.tagName.toLowerCase();)"P"!=k.tagName&&(k=k.parentNode);for(;"P"!=p.tagName&&0>p.tagName.indexOf("H")&&"table"!=p.tagName.toLowerCase();)"P"!=p.tagName&&(p=p.parentNode);"table"==k.tagName.toLowerCase()&&
(k=k.nextSibling);"table"==p.tagName.toLowerCase()&&(p=p.previousSibling);k===b&&(k=b);p===b&&(p=b);if(k===p&&k.tagName==p.tagName){if("li"!=b.tagName.toLowerCase()){for(;"P"!=b.tagName;)if(-1<b.tagName.indexOf("H"))b=r(b,h),f=document.createRange(),f.setStart(b,0),f.setEnd(b,1),n.removeAllRanges(),n.addRange(f),a=f;else if("body"==b.tagName.toLowerCase())break;else b=b.parentNode;b.setAttribute("style",d);f=document.createRange();f.setStartBefore(k);f.setEndAfter(p);n.removeAllRanges();n.addRange(f)}}else if("li"!=
b.tagName.toLowerCase()){for(;"P"!=b.tagName;)if(-1<b.tagName.indexOf("H")){b=r(b,h);f=document.createRange();f.setStart(b,0);for(k=b;b.nextSibling;)b=b.nextSibling,-1<b.tagName.indexOf("H")&&(b=r(b,h));f.setEnd(b,1);p=b;n.removeAllRanges();n.addRange(f);a=f}else if("body"==b.tagName.toLowerCase())break;else b=b.parentNode;m=k.parentNode;for(var E,F;"body"!=m.tagName.toLowerCase()&&"th"!=m.tagName.toLowerCase()&&"td"!=m.tagName.toLowerCase();)m=m.parentNode;for(var N=m.childNodes.length,l=0;l<N;l++)m.childNodes[l]===
k&&(E=l),m.childNodes[l]===p&&(F=l);for(l=E;l<=F;l++){var z=m.childNodes[l];"table"!=z.tagName.toLowerCase()&&(-1<z.tagName.indexOf("H")&&(z=r(z,h)),z.setAttribute("style",d))}f=document.createRange();f.setStartBefore(m.childNodes[E]);f.setEndAfter(m.childNodes[F]);n.removeAllRanges();n.addRange(f)}}}else if(n=_iframeDoc.getSelection(),k=a.startContainer,p=a.endContainer,t=GetTableSelectionCells(),1==a.collapsed&&0==t.length){var J=getFirstRange();a=J.range;var q=a.startContainer;m=q.parentNode;var u=
_iframeDoc.createElement("span");if("span"==a.startContainer.parentNode.tagName.toLowerCase()){var q=a.startContainer.parentNode,K=q.textContent;c=!1;for(l=0;l<q.childNodes.length;l++)if(3!=q.childNodes[l].nodeType){c=!0;break}if(c){var C=q.cloneNode();for(C.innerHTML=q.innerHTML;q.childNodes[1];)q.removeChild(q.childNodes[1]);C.removeChild(C.firstChild);q.parentNode.insertBefore(C,q.nextSibling)}else{var O=K.slice(0,a.endOffset),P=K.slice(a.endOffset);q.textContent=O;var L=q.cloneNode();L.textContent=
P;q.parentNode.insertBefore(L,q.nextSibling)}u=_iframeDoc.createElement("span");0==DEXTTOP.DEXT5.browser.gecko&&(u.innerHTML=unescape("%uFEFF"));u.setAttribute("style",d);q.parentNode.insertBefore(u,q.nextSibling)}else u=_iframeDoc.createElement("span"),0==DEXTTOP.DEXT5.browser.gecko&&(u.innerHTML=unescape("%uFEFF")),u.setAttribute("style",d),a.insertNode(u);a.selectNodeContents(u);rangy.getSelection(_iframeWin).removeAllRanges();J.sel.addRange(a);y=_dext_editor.ID;v="DEXT_Temp_Class";DEXTTOP.DEXT5.setClassStyle(y,
v);_iframeDoc.execCommand("removeFormat",!1,null);for(var x=_iframeDoc.querySelectorAll("."+v),l=0;l<x.length;l++)x[l].removeAttribute("class"),x[l].setAttribute("style",d);doSetCaretPosition(u,1)}else for(c=0;2>c;c++){y=_dext_editor.ID;v="DEXT_Temp_Class";DEXTTOP.DEXT5.setClassStyle(y,v,!0);_iframeDoc.execCommand("removeFormat",!1,null);var G=_iframeDoc.querySelectorAll("font");if(0<G.length)for(l=0;l<G.length;l++){var w=G[l],M=w.getAttribute("face")?"font-family: "+w.getAttribute("face")+";":"",
D=w.firstChild;if(3!=D.nodeType){var A=D.getAttribute("style"),A=A+M;D.setAttribute("style",A);w.parentNode.insertBefore(w.firstChild,w)}else{var H=_iframeDoc.createElement("span"),A=M;H.setAttribute("style",A);H.textContent=D.textContent;w.parentNode.insertBefore(H,w)}w.remove()}x=_iframeDoc.querySelectorAll("."+v);for(e=0;e<x.length;e++)x[e].removeAttribute("class"),x[e].setAttribute("style",d)}}catch(Q){"undefined"!=typeof RAONWIZDLW&&RAONWIZDLW&&RAONWIZDLW()}};command_p_customformatting_click=
function(a){c.show(DEXTTOP.G_CURREDITOR.ID,this)}}catch(Q){"undefined"!=typeof RAONWIZDLW&&RAONWIZDLW&&RAONWIZDLW()}})();
