(function(){try{if("undefined"!==typeof _dext_editor){var d={pluginName:"zoomslider"};G_DEPlugin.zoomslider=d;d.isSupportBrowser=!0;d._iframe=null;d._iframe_id=null;d._iframeHolder=null;d._iframeHolder_id="";d._zoomList={};d._iframe_doc=null;d._default_value="";d._maxZoom=0;d._minZoom=0;d._currZoom=0;d._self=function(){return this._iframe};d.isVisible=function(){var a=this._self();return a&&"none"!=a.style.display};d.onShowTopMenu=function(a,c){};d.onClickToolIcon=function(a){if(d.isSupportBrowser)switch(a){case "zoomslider":DEXTTOP.G_SELECTED_ELEMENT=
null;null!=this._iframe&&"ios"!=DEXTTOP.DEXT5.UserAgent.os.name.toLowerCase()||this.make(_dext_editor.ID,_dext_editor._config);G_SUB_DIALOG=this._self(_dext_editor.ID);G_CURRENT_IFRAME=DEXTTOP.DEXTDOC.getElementById(this._iframe_id);this._iframeHolder&&(G_CURRENT_IFRAME_HOLDER=DEXTTOP.DEXTDOC.getElementById(this._iframeHolder.id));DEXT5_EDITOR.prototype.dialog._click_background(!0);a=this._iframe_doc.getElementById("dext_zoom_slider");var c=this.getCurrZoom(_dext_editor);a.max=c>this._maxZoom?c:this._maxZoom;
a.min=c<this._minZoom?c:this._minZoom;a.value=c;this._iframe_doc.getElementById("dext_zoom_percent").textContent=c+"%";a={};a=getWindowScrollPos(DEXTTOP.DEXTWIN);var c=getClientRect(_iframeWin.parent.frameElement),b=null,b=getClientRect(_iframeWin.parent.frameElement.contentWindow.document.getElementById("ue_"+_dext_editor.ID+"p_zoomslider")),k=0;7==DEXTTOP.DEXT5.browser.ieVersion&&(k=-2);isFixedEditorPosition({editor:_dext_editor})&&(this._iframe.style.position="fixed",a[0]=0,a[1]=0);var f=b.left+
a[0]+c.left;isRTL(document)&&(f=this._iframeHolder?DEXTTOP.DEXT5.util.parseIntOr0(this._iframeHolder.style.width):DEXTTOP.DEXT5.util.parseIntOr0(this._iframe.style.width),f=b.right+a[0]+c.left-(f+4),0>f&&(f=10));a=b.bottom+a[1]+c.top+k;this._iframeHolder?(this._iframeHolder.style.left=f+"px",this._iframeHolder.style.top=a+"px",this._iframeHolder.style.display=""):(this._iframe.style.left=f+"px",this._iframe.style.top=a+"px");a=getClientRect(G_SUB_DIALOG);b=getClientRect(_iframeWin.frameElement);c=
parseInt(a.right,10)-parseInt(a.left,10);isRTL(document)?(G_SUB_DIALOG.style.left="0px",a=getClientRect(G_SUB_DIALOG),b=-1*c,a=a.left-c,0>a&&(b+=Math.abs(a)),G_SUB_DIALOG.style.left=b+"px"):a.left+c>=b.right&&(a=a.left+c-b.right+30,G_SUB_DIALOG.style.left=parseInt(G_SUB_DIALOG.style.left,10)-a+"px");a=this._iframe.contentWindow;var h=getIframeDocument(this._iframe);setZoomValueToBody(h,DEXTTOP.G_CURREDITOR);0==DEXTTOP.DEXT5.browser.ie&&a.focus();setTimeout(function(){h.getElementsByTagName("INPUT")[0].focus()},
1);setFocusFirstAndLast(h,h.getElementsByTagName("INPUT")[0]);try{"function"==typeof DEXTTOP.G_CURREDITOR._config.event.afterPopupShow?DEXTTOP.G_CURREDITOR._config.event.afterPopupShow(_dext_editor.ID,this._iframe,"fontsize"):"function"==typeof DEXTTOP.dext_editor_afterpopupshow_event&&DEXTTOP.dext_editor_afterpopupshow_event(_dext_editor.ID,this._iframe,"fontsize")}catch(l){"undefined"!=typeof RAONWIZDLW&&RAONWIZDLW&&RAONWIZDLW()}}};d.make=function(a,c){if(d.isSupportBrowser){var b=DEXTTOP.DEXTDOC.getElementById("dext_zoomslider_iframe_"+
a);b&&b.parentNode.removeChild(b);(b=DEXTTOP.DEXTDOC.getElementById("dext_zoomslider_iframe_holder_"+a))&&b.parentNode.removeChild(b);var k=this;k._editor_config=c;this._iframe=DEXTTOP.DEXT5.util.makeIframe();this._iframe_id="dext_pan_p_zoomslider_"+a;this._iframe.id=this._iframe_id;this._iframe.style.display="none";DEXTTOP.DEXT5.browser.iOS||DEXTTOP.DEXT5.browser.mobile?(this._iframe.width="100%",this._iframe.height="100%",this._iframe.style.overflow="hidden",this._iframe.style.display="inline-block",
this._iframeHolder=DEXTTOP.DEXTDOC.createElement("div"),this._iframeHolder_id="dext_zoomslider_iframe_holder_"+a,this._iframeHolder.id=this._iframeHolder_id,this._iframeHolder.style.display="none",this._iframeHolder.style.width="150px",this._iframeHolder.style.height="150px",this._iframeHolder.style.border="1px solid #cccccc",this._iframeHolder.style.zIndex=G_MAIN_ZINDEX+2E3+"",this._iframeHolder.style.position="absolute",this._iframeHolder.style.overflow="scroll",this._iframeHolder.style.overflowX=
"hidden",this._iframeHolder.style.webkitOverflowScrolling="touch",this._iframeHolder.appendChild(this._iframe),DEXTTOP.DEXTDOC.body.appendChild(this._iframeHolder)):(this._iframe.width="150px",this._iframe.height="40px",this._iframe.style.width="150px",this._iframe.style.height="50px",this._iframe.style.border="1px solid #cccccc",this._iframe.style.position="absolute",this._iframe.style.zIndex=G_MAIN_ZINDEX+2E3+"",this._iframe.style.overflow="",this._iframe.style.overflowX="",DEXTTOP.DEXTDOC.body.appendChild(this._iframe));
b="document.open();"+(isCustomDomain(document)?'document.domain="'+document.domain+'";':"")+" document.close();";b=DEXTTOP.DEXT5.browser.ie&&12>DEXTTOP.DEXT5.browser.ieVersion?"javascript:void(function(){"+encodeURIComponent(b)+"}())":"";this._iframe.src=b;this._iframe_doc=this._iframe.contentWindow.document;b="";isRTL(document)&&(b=' dir="rtl"');b="<html"+b+"><head><title>"+G_DEPlugin.zoomslider.lang.title+"</title>";isCustomDomain(document)&&(b+='<script>document.domain = "'+document.domain+'";\x3c/script></head>');
b+='<link href="'+_dext_editor._config.plugin_root+"zoomslider/css"+(DEXTTOP.DEXT5.isRelease?"":"_dev")+"/zoomslider.css?t="+DEXTTOP.DEXT5.UrlStamp+'" rel="stylesheet" type="text/css" />';"1"==_dext_editor._config.customCssUrlDetailApply&&(b+='<link href="'+_dext_editor._config.style.customCssUrl+"?t="+DEXTTOP.DEXT5.UrlStamp+'" rel="stylesheet" type="text/css" />');b+='</head><body  style="margin:0px; padding:4px 10px; text-align:center;" oncontextmenu="return false"></body></html>';this._iframe_doc.open("text/html",
"replace");this._iframe_doc.write(b);this._iframe_doc.close();b=document.createElement("div");b.style.alignItems="center";b.style.width="100%";var f=document.createElement("button");f.id="dext_zoomslider_decrease";f.style.cursor="pointer";var h=document.createElement("button");h.id="dext_zoomslider_increase";h.style.cursor="pointer";var l=document.createElement("button");l.id="dext_zoomslider_reset";l.style.cursor="pointer";var e=document.createElement("input");e.id="dext_zoom_slider";e.type="range";
e.min=this._minZoom;e.max=this._maxZoom;e.style.width="100%";e.style.padding="0px";var g=document.createElement("em");g.id="dext_zoom_percent";g.textContent=e.value+"%";g.setAttribute("contenteditable","true");g.style.userSelect="none";g.style.msUserSelect="none";var m=function(){g.textContent=e.value+"%";var a=_dext_editor._FRAMEWIN.document.getElementById("ue_"+_dext_editor.ID+"zoom_text");a&&(a.value=e.value+"%");command_zoom(_dext_editor.ID,_dext_editor._EDITOR.design)},n=function(a,b){a&&a.preventDefault();
DEXTTOP.DEXT5.setZoom(b,_dext_editor.ID)};f.addEventListener("click",function(){n(null,g.textContent);var a=parseInt(e.value)-10;10>a&&(a=10);a<e.min&&(e.min=a);e.value=a;m()});h.addEventListener("click",function(){n(null,g.textContent);var a=parseInt(e.value)+10;a>e.max&&(e.max=a);e.value=a;m()});l.addEventListener("click",function(){e.value=100;m()});DEXTTOP.DEXT5.browser.ie&&11>=DEXTTOP.DEXT5.browser.ieVersion?DEXTTOP.DEXT5.util.addEvent(e,"change",m):DEXTTOP.DEXT5.util.addEvent(e,"input",m);g.addEventListener("keydown",
function(a){var b=a.key||a.keyCode;"Enter"!==b&&13!==b||n(a,this.textContent)});b.appendChild(f);b.appendChild(h);b.appendChild(l);b.appendChild(g);this._iframe_doc.body.appendChild(e);this._iframe_doc.body.appendChild(b);DEXTTOP.DEXT5.util.addEvent(k._iframe_doc,"keyup",function(a){27==("which"in a?a.which:a.keyCode)&&(k.hide(),setTimeout(function(){setFocusToBody()},1))})}};d.getCurrZoom=function(a){var c=a.getEditorMode(),b=null;"design"==c?b=a._EDITOR.design.contentDocument.body:"preview"==c&&
(b=a._EDITOR.preview.contentDocument.body);a=/\((.*)\)/i;c=100;b&&b.style.transform.match(a);return c=""==RegExp.$1?100:Math.round(100*parseFloat(RegExp.$1))};d.hide=function(){d.isSupportBrowser&&(dialogCancel(),G_SUB_DIALOG=this._self(),DEXT5_EDITOR.prototype.dialog._click_background(!0),this._iframe.style.display="none",this._iframeHolder&&(this._iframeHolder.style.display="none"))};d.onDisableToolIcon=function(a){if(d.isSupportBrowser)switch(a){case "allDisable":return["p_zoomslider"];default:return!1}};
d.applyChangeToIframe=function(a){a=DEXTTOP.DEXT5.util.parseIntOr0(a);0==a?a=this.getCurrZoom(_dext_editor):10>a&&(a=10);var c=this._self().contentDocument.getElementById("dext_zoom_slider");c.max<a?c.max=a:c.min>a&&(c.min=a);c.value=a;this._self().contentDocument.getElementById("dext_zoom_percent").textContent=a+"%"};d.onCreateContextMenu=function(a){};d.onInit=function(){if(!_dext_editor._config.zoomList||DEXTTOP.DEXT5.browser.ie&&10>DEXTTOP.DEXT5.browser.ieVersion){d.isSupportBrowser=!1;var a=
_dext_editor;a.remove_item.push("p_zoomslider");a._config.removeItem.push("p_zoomslider")}else{var a="../plugin/zoomslider/js"+(DEXTTOP.DEXT5.isRelease?"":"_dev")+"/config.js",a="1"==DEXTTOP.G_CURREDITOR._config.useConfigTimeStamp?a+("?t="+DEXTTOP.DEXT5.util.getTimeStamp()):a+("?t="+DEXTTOP.DEXT5.UrlStamp),c={url:_dext_editor._config.webPath.plugin+"zoomslider/js"+(DEXTTOP.DEXT5.isRelease?"":"_dev")+"/lang/"+_dext_editor._config.lang+".js",targetDocument:document};loadScript({url:a,targetDocument:document},
function(){var a=document.getElementById("zoom_"+_dext_editor.ID+"_holder");a&&G_DEPlugin.zoomslider.config&&!G_DEPlugin.zoomslider.config.displayStatusBarZoom&&(a.style.display="none")});loadScript(c,null)}};d.onInit();d.onLoaded=function(){var a=_dext_editor._config.zoomList.map(function(a){return parseInt(a,10)||0});this._minZoom=Math.min.apply(0,a);this._maxZoom=Math.max.apply(0,a)}}}catch(p){"undefined"!=typeof RAONWIZDLW&&RAONWIZDLW&&RAONWIZDLW()}})();
