(function(){try{var a={pluginName:"forbiddenword"};G_DEPlugin.forbiddenword=a;if(DEXTTOP.DEXT5.browser.ie&&7>=DEXTTOP.DEXT5.browser.ieVersion){var m=DEXTTOP.G_CURREDITOR._config.toolBar1.indexOf("p_forbiddenword"),n=DEXTTOP.G_CURREDITOR._config.toolBar2.indexOf("p_forbiddenword");-1<m&&DEXTTOP.G_CURREDITOR._config.toolBar1.splice(m,1);-1<n&&DEXTTOP.G_CURREDITOR._config.toolBar2.splice(n,1)}a.onInit=function(){loadScript({url:_dext_editor._config.webPath.plugin+"forbiddenword/js"+(DEXTTOP.DEXT5.isRelease?
"":"_dev")+"/lang/"+_dext_editor._config.lang+".js",targetDocument:document},null)};a.onClickToolIcon=function(){try{if(1!=a.isProcess){a.isProcess=!0;showProcessingBackground();var p=DEXTTOP.G_CURREDITOR._BODY.innerText;if(DEXTTOP.DEXT5.IsEmpty(DEXTTOP.G_CURREDITOR.ID))return alert(dext5_lang.plugins.forbiddenword.no_content),a.isProcess=!1,hideProcessingBackground(),!1;var h=DEXTTOP.G_CURREDITOR._config.forbiddenWord,b=h.split(","),f=[];b.sort(function(c,f){if(c.length<f.length)return 1;if(c.length>
f.length)return-1;var a=c,b=f,d=null,h="number"==typeof b&&"number"==typeof a;if(!h){for(var g=a.length,k=b.length,p="",l="",r="",e=0;e<g&&!(e+1>k);e++){var m=a.substring(e,e+1),n=b.substring(e,e+1);if(m==n)p=a.substring(e+1),l=b.substring(e+1),r=isNaN(parseInt(m,10))||isNaN(parseInt(n,10))?"":r+m;else break}""!=p&&(a=r+p);""!=l&&(b=r+l);if(!isNaN(parseInt(a.substring(0,1),10))&&!isNaN(parseInt(b.substring(0,1),10)))if(parseInt(b,10)!=parseInt(a,10))d=parseInt(b,10)>parseInt(a,10);else{g=a.length;
for(e=d=0;e<g;e++)if(isNaN(parseInt(a.substring(e,e+1),10))){d=e;break}g=b.length;for(e=k=0;e<g;e++)if(isNaN(parseInt(b.substring(e,e+1),10))){k=e;break}d=k<d}}null==d&&(d=h?b>a:DEXTTOP.DEXT5.browser.opera||DEXTTOP.DEXT5.browser.chrome?0>a.localeCompare(b,"en-us"):0>a.localeCompare(b));return d?1:-1});if(""!=h&&null!=h&&void 0!=h)for(h=0;h<b.length;h++){var g=null;if(g=p.match(new RegExp(b[h],"ig")))for(var c=0,d=0;d<g.length;d++){var c=p.indexOf(g[d],c),l={word:g[d],indexOf:c},c=c+b[h].length;f.push(l);
for(var k=0;k<f.length-1;k++)-1<f[k].word.indexOf(l.word)&&f[k].indexOf<=l.indexOf&&f[k].indexOf+f[k].word.length>=l.indexOf&&f.splice(f.length-1,1)}}if(0==f.length)return alert(dext5_lang.plugins.forbiddenword.compMsg),a.isProcess=!1,hideProcessingBackground(),!1;f.sort(function(a,b){return a.indexOf>b.indexOf?1:a.indexOf<b.indexOf?-1:0});a.chkWordArr=f;DEXT5_EDITOR.prototype.dialog.show(_dext_editor._config.webPath.plugin,"forbiddenword/editor_popup.html");hideProcessingBackground()}}catch(m){a.isProcess=
!1,hideProcessingBackground()}};a.setPopup=function(a,h,b){try{var f=DEXTTOP.DEXTDOC.getElementById("dext_frame_"+DEXTTOP.G_CURREDITOR.ID).contentWindow,g=f.rangy.createRange(b.document.getElementById("copycontent").contentWindow.document);if(0==a.length)return!1;for(var c=0;c<a.length;c++)if(g.findText(a[c].word)){g.deleteContents();var d=b.document.createElement("span");d.setAttribute("id","cnt"+c);d.setAttribute("class","cnt");d.setAttribute("onmouseover","parent.forbidden_word_over(this)");d.setAttribute("onmouseout",
"parent.forbidden_word_out(this)");var l=document.createElement("span");l.setAttribute("class","wordspan");l.innerText=a[c].word;var k=b.document.createElement("sup"),m=b.document.createTextNode(c+1+")");k.appendChild(m);d.appendChild(k);d.appendChild(l);g.insertNode(d);g.selectNode(d);h?g.collapse(!1):g.collapse(!0);var q=b.document.createElement("dl");q.setAttribute("id","list"+c);q.setAttribute("value",c);-1!=f.G_DEPlugin.forbiddenword.chkWordArr[c].word.indexOf("'")?q.innerHTML='<div class="forbiddenDiv"><div class="forbiddenWord" onclick="scroll_to_text_click(this)"><p>'+
(c+1)+") "+f.G_DEPlugin.forbiddenword.chkWordArr[c].word+'</p></div><div class="forbiddenBtn"><button onclick="delete_btn_click(this)" class="forbiddenDBtn">'+dext5_lang.plugins.forbiddenword.word_delete+'</button> <button onclick="permit_btn_click(this)" class="forbiddenPBtn">'+dext5_lang.plugins.forbiddenword.permit+"</button>":q.innerHTML+="<div class='forbiddenDiv'><div class='forbiddenWord' onclick='scroll_to_text_click(this)'><p>"+(c+1)+") "+f.G_DEPlugin.forbiddenword.chkWordArr[c].word+"</p></div><div class='forbiddenBtn'><button onclick='delete_btn_click(this)' class='forbiddenDBtn'>"+
dext5_lang.plugins.forbiddenword.word_delete+"</button> <button onclick='permit_btn_click(this)' class='forbiddenPBtn'>"+dext5_lang.plugins.forbiddenword.permit+"</button>";b.document.getElementById("wordlist").appendChild(q)}hideProcessingBackground()}catch(n){"undefined"!=typeof RAONWIZDLW&&RAONWIZDLW&&RAONWIZDLW()}};a.onInit()}catch(t){"undefined"!=typeof RAONWIZDLW&&RAONWIZDLW&&RAONWIZDLW()}command_forbidden_word=function(m,h,b){a.callbackType=b;a.onClickToolIcon()}})();
