(function(){try{var c={pluginName:"lazyload",cssUrl:DEXTTOP.G_CURREDITOR._config.webPath.plugin+"lazyload/css/lazyload.css"+("1"==DEXTTOP.DEXT5.config.UseConfigTimeStamp?"?t="+DEXTTOP.DEXT5.util.getTimeStamp():"?t="+DEXTTOP.DEXT5.UrlStamp),cssId:"dextLazyCss",isSupported:"function"==typeof document.getElementsByClassName?!0:!1,isLoadError:!1,isLoadedComplete:!1,canUseLazyLoad:function(){return 1==c.isSupported&&0==c.isLoadError&&1==c.isLoadedComplete}};G_DEPlugin.lazyload=c;var b=null;if(0!=c.isSupported){c.onInit=
function(){var a="../plugin/lazyload/js"+(DEXTTOP.DEXT5.isRelease?"":"_dev")+"/config.js",a="1"==DEXTTOP.DEXT5.config.UseConfigTimeStamp?a+("?t="+DEXTTOP.DEXT5.util.getTimeStamp()):a+("?t="+DEXTTOP.DEXT5.UrlStamp),a={url:a,targetDocument:document};loadScript({url:_dext_editor._config.webPath.plugin+"lazyload/js"+(DEXTTOP.DEXT5.isRelease?"":"_dev")+"/lang/"+_dext_editor._config.lang+".js",targetDocument:document},null);loadScript(a,function(a){if(0==a)c.isLoadError=!0,c.isLoadedComplete=!0;else if(G_DEPlugin.lazyload.options){window.lazySizesConfig=
{lazyClass:"dext_lazyload",loadedClass:"dext_lazyloaded",loadingClass:"dext_lazyloading",preloadClass:"dext_lazypreload",errorClass:"dext_lazyerror",autosizesClass:"dext_lazyautosizes",fastLoadedClass:"dext_ls-is-cached",srcAttr:"dext-src",srcsetAttr:"dext-srcset",sizesAttr:"dext-sizes"};for(var d in G_DEPlugin.lazyload.options)window.lazySizesConfig[d]=G_DEPlugin.lazyload.options[d];a="../plugin/lazyload/js"+(DEXTTOP.DEXT5.isRelease?"":"_dev")+"/lazysizes.js";a="1"==DEXTTOP.DEXT5.config.UseConfigTimeStamp?
a+("?t="+DEXTTOP.DEXT5.util.getTimeStamp()):a+("?t="+DEXTTOP.DEXT5.UrlStamp);loadScript({url:a,targetDocument:document},function(a){c.isLoadedComplete=!0;1==a?"undefined"!=typeof lazySizes&&(b=lazySizes):c.isLoadError=!0})}})};c.onInit();c.onLoaded=function(){};c.onBeforeGetApi=function(a){if(c.canUseLazyLoad()){var b=a.targetDoc.getElementById(c.cssId);b&&b.parentNode.removeChild(b);n(a)}};c.onAfterGetApi=function(a){a=c.replaceLazySrc(a.html);try{for(var h=_iframeDoc.getElementsByTagName("img"),
d=h.length,e=0;e<d;e++){var k=h[e],l=k.getAttribute(b.cfg.srcAttr);"string"==typeof l&&""!=l&&0>k.className.indexOf(b.cfg.lazyClass)&&b.aC(k,b.cfg.lazyClass)}}catch(f){"undefined"!=typeof RAONWIZDLW&&RAONWIZDLW&&RAONWIZDLW()}return a};c.onBeforeEditorChangeMode=function(a){c.canUseLazyLoad()&&("source"==a.newMode?n({targetDoc:_iframeDoc}):"preview"==a.currMode&&"design"==a.newMode&&m(_iframeWin))};c.onAfterEditorChangeMode=function(a){if(c.canUseLazyLoad())if("preview"==a.newMode)m(DEXTTOP.G_CURREDITOR._EDITOR.preview.contentWindow);
else if("source"==a.newMode){a=DEXTTOP.G_CURREDITOR._EDITOR.source;var b=a.value,b=c.replaceLazySrc(b);a.value=b}};c.isRequiredCheck=function(a){return c.isLoadedComplete};c.onBeforeDocumentWrite=function(a){var h={html:null};if(c.canUseLazyLoad()){a=a.html;var d=new RegExp(/(<img[^>]+)(src=)([^>]+>)/gi);if(d.test(a))try{a=a.replace(d,"$1"+b.cfg.srcAttr+"=$3")}catch(e){"undefined"!=typeof RAONWIZDLW&&RAONWIZDLW&&RAONWIZDLW()}h.html=a}return h};c.onAfterDocumentWrite=function(a){if(c.canUseLazyLoad()){a=
_iframeDoc.getElementsByTagName("img");for(var h=a.length,d=0;d<h;d++)for(var e=a[d],k=e.attributes.length,l=0;l<k;l++){var f=e.attributes[l];f.name==b.cfg.srcAttr&&""!=f.value?0==b.hC(e,b.cfg.lazyClass)&&b.aC(e,b.cfg.lazyClass):-1<f.name.indexOf(b.cfg.srcAttr)&&(e.setAttribute(f.name.replace(b.cfg.srcAttr,"src"),f.value),e.removeAttribute(f.name))}m(_iframeWin)}};c.replaceLazySrc=function(a){return a=a.replace(new RegExp("<img[^>]*? "+b.cfg.srcAttr+"=","gi"),function(a){return a.replace(" "+b.cfg.srcAttr+
"="," src=")})};var m=function(a){var h=function(){_iframeDoc.addEventListener("lazyloaded",p);b.setWindow(a);setTimeout(function(){b.init(!0)},0)};null==a.document.getElementById(c.cssId)?q(a.document,h):h()},p=function(a){},n=function(a){for(var c=[b.cfg.lazyClass,b.cfg.loadedClass,b.cfg.loadingClass,b.cfg.preloadClass,b.cfg.errorClass,b.cfg.autosizesClass,b.cfg.fastLoadedClass],d=c.length,e=0;e<d;e++)for(var k=a.targetDoc.getElementsByClassName(c[e]),l=c[e],f=k.length-1;0<=f;f--){var g=k[f];g.getAttribute(b.cfg.srcAttr)&&
"string"==typeof g.getAttribute("src")&&(g.getAttribute("src")!=g.getAttribute(b.cfg.srcAttr)&&g.setAttribute(b.cfg.srcAttr,g.getAttribute("src")),g.removeAttribute(b.cfg.srcAttr));b.rC(g,l);""!=g.className&&""!=g.className.replace(/ /g,"")||g.removeAttribute("class")}},q=function(a,b){var d=a.createElement("link");d.href=c.cssUrl;d.id=c.cssId;d.rel="stylesheet";d.type="text/css";d.onload=function(){b()};a.getElementsByTagName("head")[0].appendChild(d)}}}catch(r){"undefined"!=typeof RAONWIZDLW&&RAONWIZDLW&&
RAONWIZDLW()}})();
